environment.sample, opencodelists/settings.py, requirements.in, requirements.txt
The appropriate DSN has already been added to the production config so
this should start working as soon as it's deployed.
=> Add Sentry for alerting and debugging support

opencodelists/settings.py, templates/base.html, templates/registration/login.html
This adds Sign in and Sign out links to the nav bar based on a Users authenticated state.
I've reworded the submit button to match the nav links (and flipped it to use Bootstrap's `btn` styles just to be consistent with the index page).
=> Add Sign in and Signout Links

.pre-commit-config.yaml, Makefile, README.md, pyproject.toml, requirements.in, requirements.txt
[Pre-Commit](https://pre-commit.com/) is a framework for running tools before committing via Git's pre-commit hook.
I find it really useful as a smoke test before committing since it runs the configured tools on the diff being committed, and for many of them will do the Right Thing™ (eg black will modify the files which need changes).  It also isn't a requirement, so if this flow doesn't work for someone they can simply not install the hook.
=> Add Pre-Commit

codelists/tests/test_views.py, pyproject.toml
This… is the final commit I forgot to push 🤦
=> Signoffs and references Part2

builder/views.py, static/js/builder.js
This PR refactors builder.js.  It breaks a big component up into lots of smaller ones, and uses props correctly.
=> Refactor builder.js

builder/actions.py, codelists/hierarchy.py, codelists/tests/test_hierarchy.py
@ghickman please could you review to check that the code + comments in `hierarchy.py` makes sense, and that you're happy with the tests?
=> Add Hierarchy class

codelists/definition.py, codelists/tests/test_definition.py, codelists/tree_utils.py, codelists/views.py
Suggest reviewing commit-by-commit.
=> Use hierarchies to build definitions

codelists/forms.py, codelists/tests/test_forms.py
=> Remove byte order mark from uploaded CSVs

builder/views.py, static/js/builder.js, templates/builder/codelist.html
@ghickman please don't feel you need to review the JS in depth -- there are several changes I'd like to make to it (including not running the "test suite" on each page load, ahem) and large parts are not adequately commented yet.  But a sense check would be appreciated!
=> Use hierarchies in JS

codelists/tests/test_definition.py, requirements.in, requirements.txt
This lets each subtest output to the console like a normal test, so in normal mode you'll see a `.` for each subtest.
=> Use pytest-subtests for subtests

fabfile.py
This enables [release tracking](https://docs.sentry.io/product/releases/) in Sentry.
I've not tested this yet because I wanted to get some review before I tried it out.
=> Notify sentry of a release after deploying

codelists/templatetags/definitions.py
=> Convert coding system ID for URL reversing

static/src/js/builder.jsx, static/src/js/hierarchy.js
=> Restructure JS

coding_systems/snomedct/urls.py, coding_systems/snomedct/views.py, mappings/ctv3sctmap2/mappers.py, templates/snomedct/history_substitutions.html
The mega commit message is mostly for future documentation -- if anything there doesn't make sense, let me know.
=> Stop using History Substitution Table to generate SNOMED CT codelists

package-lock.json, package.json, static/src/js/builder/codelistbuilder.jsx, static/test/js/builder/codelistbuilder.test.js
This adds (a) a very basic tooltip when you hover over a question mark and (b) more comprehensive tests that will allow us to do the plumbing to make changes to the tooltip.
=> Add tooltips

mappings/ctv3sctmap2/mappers.py, mappings/ctv3sctmap2/tests/test_mappers.py
This adds a function to convert SNOMED CT concept codes to CTV3 concept codes using the assured mappings.
Fixes #201
=> Convert SNOMED codes -> CTV3 codes

codelists/models.py, codelists/views.py, conversions/forms.py, conversions/urls.py, conversions/views.py, mappings/ctv3sctmap2/mappers.py, opencodelists/urls.py, templates/conversions/convert.html
This is about the simplest thing that's useful, and only allows for conversions from SNOMED CT to CTV3, which is most urgent.
There are no tests yet -- I'll add some once we've worked out whether this is something people actually need.
=> Add page for converting codelists between coding systems 

conversions/urls.py, conversions/views.py
This addresses @ghickman's comments on #212.
=> Smarten up conversion code

static/src/js/builder/codelistbuilder.jsx, static/src/js/builder/index.jsx, static/src/js/utils.js, templates/builder/codelist.html
@ghickman do you have any better ideas for fixing 7d98862c0dfa2e203a51c443d6148f26bcd51772?
=> JS housekeeping

.github/workflows/main.yml, .pre-commit-config.yaml, Makefile, deploy/bin/backup.sh, deploy/bin/start_service.sh, deploy/cron/opencodelists, fabfile.py
We back up data from just the apps that have user-created data.
=> Add cronjob to back up database every night

mappings/bnfdmd/mappers.py
As requested by Brian.
@ghickman this is hard to review without knowing anything about the [dm+d](https://www.thedatalab.org/blog/2019/08/81/what-is-the-dmd-the-nhs-dictionary-of-medicines-and-devices/)!  Suggest checking that the code changes look sensible.
=> Don't include product packs in in dm+d codelists

builder/actions.py
The calls to get_or_create were inefficient.  With this change, creating
a search for "tia" takes ~5s, down from >30s.
This addition highlights a poor terminology choice on my part.
builder.models.Code should be called something like
builder.models.CodeObj, to distinguish it from a concept code.
Fixes #330.
=> Make builder.actions.create_search more efficient

templates/codelists/version.html
Missed out of feb35a79696ae6f70f6d3a427242fdea899da55c.
=> Only show edit buttons to authorised users

builder/actions.py, builder/tests/test_actions.py, builder/tests/test_views.py, builder/urls.py, builder/views.py, static/src/js/builder/codelistbuilder.jsx, templates/builder/codelist.html
This is next baby step towards allowing uploaded codelists to be edited.
=> Allow for non search codes in builder

opencodelists/hash_utils.py
=> Remove dodgy assert

codelists/models.py, codelists/presenters.py, codelists/views/version.py, templates/codelists/_search_results.html, templates/codelists/version.html
This does not have tests, which will follow when we have improved our
fixtures.
=> Show search terms on version page

codelists/models.py, templates/codelists/version.html
=> Fix organisation references on version page

codelists/models.py, codelists/views/version.py
You've guessed it: tests to follow
=> Show edit buttons on user codelist

codelists/models.py, codelists/tests/test_models.py, conftest.py, opencodelists/tests/assertions.py, opencodelists/tests/fixtures.py, opencodelists/tests/test_actions.py, opencodelists/tests/test_views.py
This introduces a new fixtures module, with a universe of fixtures that should be sufficient for testing all existing functionality.
The goal is to replace all existing fixtures and factories with fixtures in this module.
=> Fix fixtures

opencodelists/admin.py, opencodelists/models.py
This is to allow admin users eg @CarolineMorton to help users reset their password.
=> Display password reset link in admin

builder/actions.py, builder/management/commands/generate_builder_fixture.py, codelists/models.py, codelists/views/version_download.py, pyproject.toml
Also includes a couple of other random commits from the branch I was working on, sorry.
=> Fix CSV download

fabfile.py
* this means the service will start automatically when the host machine is restarted
=> Enable the service

codelists/models.py, opencodelists/csv_utils.py
=> Fix dm+d download

coding_systems/ctv3/coding_system.py, coding_systems/snomedct/coding_system.py
This is already supported for BNF codes
=> Allow searching for codes in builder

codelists/actions.py, codelists/api.py, codelists/api_urls.py, codelists/models.py, codelists/tests/test_actions.py, codelists/tests/test_api.py, opencodelists/actions.py, opencodelists/models.py, opencodelists/settings.py, opencodelists/tests/fixtures.py, opencodelists/tests/test_actions.py, opencodelists/urls.py, pyproject.toml, requirements.in, requirements.txt
It's not yet clear how much of an API we'll need and using DRF is a bit of a sledgehammer for this endpoint -- but it may prove useful if we want to extend the API in future.  At the moment, we're only really using it for authentication.
=> Add API endpoint for creating new codelist versions

coding_systems/opcs4/coding_system.py
This is enough to make OPCS-4 appear in the dropdown for coding systems
on the CSV upload page
=> Add basic OPCS-4 coding system

codelists/models.py
=> Reinstate cached_property

templates/codelists/_tab_pane.html, templates/codelists/version.html
=> Show About tab content when page is loaded

coding_systems/null/coding_system.py
This is to allow for eg uploading lists of high-cost drugs
=> Add null coding system

templates/base.html
CSS based on https://getbootstrap.com/docs/4.1/examples/sticky-footer/.
=> Add SNOMED CT and ICD-10 copyright notices

templates/codelists/index.html
=> Add banner with links to videos and docs

templates/base.html, templates/codelists/index.html
=> Add introduction and videos to homepage

templates/codelists/index.html
Notes to reviewers:
* add `?w=1` to the URL when viewing a diff to ignore whitespace changes
* test failures are linting errors -- I merged a PR that bumped eslint-xxx when I meant to merge eslint-yyy...
=> Minor tweaks to homepage

templates/base.html
=> Fix alignment of navbar headings

templates/codelists/version.html
=> Expose version hash

fabfile.py
This is a hangover from when fabric ran as root
=> Don't chown everything on deploy

coding_systems/icd10/import_data.py
I have verified that the codes output by this change matches the codes
published by the WHO in their own browser at
https://icd.who.int/browse10/2019/en.
=> Fix ICD-10 importer to handle modified codes

codelists/codeset.py, static/src/js/common/tree-tables.jsx, static/src/js/hierarchy.js
These changes take the time to process including/excluding a code in a large codelist from ~10s to ~2.5s.
=> Improve performance of the builder

codelists/codeset.py, static/src/js/common/tree-tables.jsx, static/src/js/hierarchy.js
Reverts opensafely-core/opencodelists#707
It's broken the expand/collapse behaviour.
=> Revert "Improve performance of the builder"

docs/views.py, environment.sample, opencodelists/models.py, opencodelists/settings.py, templates/base.html, templates/codelists/index.html
Reverts opensafely-core/opencodelists#714
=> Revert "Change name to OpenCodelists"

docs/views.py, environment.sample, opencodelists/models.py, opencodelists/settings.py, templates/base.html, templates/codelists/index.html
Reverts opensafely-core/opencodelists#715
=> Revert "Revert "Change name to OpenCodelists""

README.md, templates/docs/index.html
In the README and documentation index page.
=> Update OpenCodelists URL

codelists/presenters.py, codelists/tests/test_presenters.py, templates/codelists/_search_results_tab.html
=> Fix search tab

.prettierignore, DEPLOY.md, README.md
* Add OpenSAFELY framework section.
* Move deployment info to DEPLOY.md
=> Tidy the README

deploy/bin/backup.sh
* use built-in fixtures compression feature https://docs.djangoproject.com/en/3.2/ref/django-admin/#fixtures-compression
=> Compress backup files

templates/base.html
To use the IE11 compatible code.
=> Update Plausible Analytics code

.github/dependabot.yml
This stops Peter and George from getting even more notifications 🙉
=> Stop Setting Reviewers on Dependabot PRs

codelists/forms.py, codelists/tests/test_forms.py
=> feat: Clean csv header

codelists/forms.py, codelists/tests/test_forms.py
This reverts commit 9193e7fc1ef5e1f309e4b62369b3458a3e9d5809.
=> Revert "feat: Clean csv header (#1063)"

DEPLOY.md, opencodelists/settings.py, requirements.prod.in, requirements.prod.txt, templates/base.html, templates/registration/login.html, templates/registration/password_change_done.html, templates/registration/password_change_form.html, templates/registration/password_reset_complete.html, templates/registration/password_reset_confirm.html, templates/registration/password_reset_done.html, templates/registration/password_reset_email.html, templates/registration/password_reset_form.html, templates/registration/password_reset_subject.txt
Fixes #1047 
Uses django's auth urls/views, so just requires adding relevant templates, and setting up email.
=> Allow users to change and reset their own passwords

CHECKS, codelists/models.py, opencodelists/models.py, opencodelists/tests/fixtures.py, opencodelists/tests/views/test_user.py, opencodelists/views/user.py
Post-merge updates from 
#1132 
#1133 
#1129
=> Various updates from recent PRs

deploy/gunicorn/conf.py, dotenv-sample, pyproject.toml, requirements.prod.in, requirements.prod.txt
* send spans to honeycomb.io
* @madwort  has added the new envvars to the app config on dokku1
=> feat: add opentelemetry

.pre-commit-config.yaml, codelists/api.py, codelists/tests/test_api.py
Fixes https://github.com/opensafely-core/opencodelists/issues/1189.
=> Add coding_system_id parameter to codelist list API endpoint

opencodelists/urls.py, static/robots.txt
* ask nicely for scraper bots to go easy on us 
* redirect from the required location opencodelists.org/robots.txt to the static file at opencodelists.org/static/robots.txt
=> feat: add a robots.txt

codelists/forms.py, codelists/tests/test_forms.py
We turned off quote handling in CSV uploading to handle confusing cases
where headers contained extraneous whitespace (see #1065).  However,
that meant that we could not handle CSVs with commas (#1210).
Instead of attempting to handle CSVs with whitespace in headers, we now
raise a ValidationError, which allows us to to handle quotes properly.
Fixes #1210.
=> Handle quotes in CSV files as expected

templates/docs/index.html
Add links to OpenSAFELY and who we are.
=> Add links at top of docs

userdocs/what-is-a-codelist.md
In the "What is a codelist?" section of the user docs.
=> Fix text formatting

templates/base.html, templates/codelists/_about_tab.html, templates/codelists/_tab_pane.html, templates/codelists/version.html
=> Add disclaimer to codelist "about" tab

codelists/forms.py, codelists/tests/test_forms.py, opencodelists/forms.py
Previously we would blow up with an exception.
Closes #1548
=> Ignore blank lines in CSV upload

codelists/actions.py, codelists/management/commands/update_draft.py, coding_systems/base/coding_system_base.py, coding_systems/bnf/coding_system.py, coding_systems/bnf/tests/test_coding_system.py, coding_systems/ctv3/coding_system.py, coding_systems/ctv3/tests/test_coding_system.py, coding_systems/icd10/coding_system.py, coding_systems/icd10/tests/test_coding_system.py, coding_systems/snomedct/coding_system.py, coding_systems/snomedct/tests/test_coding_system.py
Some more efficiency improvements when creating and updating new draft versions
=> Make updating drafts more efficient

coding_systems/dmd/import_data.py
Hopefully fixes #1571 
dm+d imports have been failing since 10th July.  There's no specific error, and it runs OK locally, but the process is killed at some point during the import on dokku3. When I ran it manually and watched htop, it looks like it's maxing out memory.
This PR is an attempt to decrease memory usage by using generators etree's `iter` methods wherever possible, and avoid turning the entire loaded data files into lists.  I used `tracemelloc.get_traced_memory()` as a basic comparison (wrapped around the `import_coding_system()` call on line 57), and ran the entire import with the old and new code. Reported peak memory for the old code was 130,356,648, and for the new code (this PR) it was 186,501, so hopefully this is enough to fix the imports on dokku3 (but can't tell for …
=> Make dmd imports more memory efficient

codelists/models.py, codelists/tests/views/test_version_download.py
VMP codes in the dm+d coding system can change; the imported data provides us with a mapping at each release of current VMP to previous VMP, and OpenCodelists maintains a list of those mappings and updates it with each release.
dm+d CSV downloads automatically add in codes for VMPs that were previously (or subsequently) mapped to any code in the codelist.
e.g. Assume we have a codelist `["a", "b", "c"]`
And in the mappings we have:
```
("a", "d"),
("b", "e"),
("e", "f")
```
So VMP "a" replaced VMP "d"; VMP "b" replaced VMP "e", and sometime in the past VMP "e" replaced VMP "f".
When we download this codelist we have to map in any codes that map to any code in the codelist, even if they're more than one step away.  In this case, we need to map in "d" and "e", which are immediately …
=> Allow mapping of previous VMPs more than one step from codelist codes

static/dist/robots.txt
* they have recently ramped up their scraping of us
=> chore: add DotBot to robots.txt

docker/Dockerfile, docker/docker-compose.yaml, docker/justfile
=> Run as non-root user in docker

.github/workflows/main.yml, .gitignore, DEVELOPERS.md, codelists/scripts/import_codelists_from_xlsx.py, docker/Dockerfile, docker/docker-compose.yaml, docker/entrypoints/prod.sh, docker/justfile, dotenv-sample, justfile, opencodelists/settings.py
Trying to do the run-as-non-root user properly this time.
- unrevert the previous commits to run as non-root
- update dockerfile/docker-compose following job-server example
- add smoketest for prod image
=> Run as non-root user

docker/justfile, opencodelists/settings.py
- fix asset configuration when in docker
- allow multiple invocations of just docker/serve to work
=> fix docker asset config

package-lock.json, package.json, static/src/js/builder/index.jsx, static/src/js/tree/index.jsx
Closing various dependabot PRs.
Closes #1808
Update React root location: https://react.dev/blog/2022/03/08/react-18-upgrade-guide#updates-to-client-rendering-apis
=> Update JS dependencies

userdocs/creating-a-codelist-from-scratch.md
Including a link to streamlit app for exploring SNOMED code usage.
=> Add section on choosing appropriate codes

.github/dependabot.yml
And group npm updates in to development and production.
=> Update dependabot config to weekly updates

codelists/scripts/import_codelists_from_xlsx.py, docker/entrypoints/check.sh, justfile, manage.py, pyproject.toml, requirements.dev.in, requirements.dev.txt
Fixes #2037.
Inspired by #2121; let's switch to using Ruff for formatting as well as linting, like we do in job-server.
=> Switch to Ruff for formatting

assets/src/scripts/__tests__/builder/codelistbuilder.test.jsx, assets/src/styles/base.css, biome.json, docker/Dockerfile, package-lock.json, package.json
=> Replace ESLint and Prettier with Biome

CHECKS, app.json
=> Move healthcheck to `app.json`

CHECKS, app.json
This reverts the commits added by #2129.
=> Revert move healthcheck to `app.json`

codelists/api.py
=> Document API endpoint clients and `versions` purpose

opencodelists/settings.py, opencodelists/tests/views/test_register.py
=> Apply password validation in all environments

deploy/bin/import_latest_bnfdmd_cronfile
Friday night is a silly time to do this when no-one is in the next morning. Let's do it on a Wednesday
=> Move bnfdmd import to Wednesday

mappings/bnfdmd/README
Add automated process and what to do if it goes wrong.
=> Update bnfdmd readme

codelists/scripts/README.md, codelists/scripts/bulk_import_codelists.py, codelists/scripts/nhsd_primary_care_refsets.json, codelists/tests/fixtures/codelists.txt, codelists/tests/test_bulk_import_codelists.py
=> Bulk loading of NHSD primary care refsets

opencodelists/management/commands/remove_spam_users.py
=> Remove spam users

docker/docker-compose.yaml, justfile, opencodelists/settings.py, requirements.prod.in, requirements.prod.txt
=> Remove `environs`

opencodelists/management/commands/remove_spam_users.py
Minor changes following git snafu
=> Fixup 1bc7740

assets/src/scripts/__tests__/builder/codelistbuilder.test.jsx, assets/src/scripts/builder/index.jsx, package-lock.json, package.json
- Remove unused babel-loader dependency – this was used in the webpack pipeline which was removed (https://github.com/opensafely-core/opencodelists/pull/1257)
- Remove ESLint comments - as we switched to Biome for linting (https://github.com/opensafely-core/opencodelists/pull/2121)
=> Remove unused comments and dependency

assets/src/scripts/_utils.js, assets/src/scripts/builder/index.jsx, assets/src/scripts/components/CodelistBuilder.jsx, assets/src/scripts/components/DescendantToggle.jsx, assets/src/scripts/components/Filter.jsx, assets/src/scripts/components/MoreInfoModal.jsx, assets/src/scripts/components/Pipes.jsx, assets/src/scripts/components/StatusToggle.jsx, assets/src/scripts/components/TreeRow.jsx, assets/src/scripts/tree/index.jsx
Identified as part of #2249 – these fixes are listed in individual commits to improve the code quality of the React applications, and prepare for a TypeScript migration.
=> Various React and JS fixes for builder and tree apps

.gitignore
This output file can contain PII so we definitely don't want to commit it to git.
=> Gitignore remove_spam_users management command output

deploy/bin/backup.sh
=> Fix sentry functions import for backups

0002-backup-sanitisation.md, DEVELOPERS.md, deploy/bin/backup.sh, deploy/bin/sanitise_backup.py, opencodelists/management/commands/create_user.py, opencodelists/tests/integration/test_sanitise_backup.py, opencodelists/tests/management/commands/test_create_user.py, requirements.prod.in, requirements.prod.txt
Make a PII-free copy of the backup for developer use
=> Sanitise backups

templates/_components/form_input.html, templates/_components/registration_form.html, templates/_components/site_message.html, templates/_icons/check_circle_mini.svg, templates/_icons/chevron_down_mini.svg, templates/_icons/chevron_up_mini.svg, templates/_icons/exclamation_circle_mini.svg, templates/_icons/exclamation_triangle_mini.svg, templates/_icons/x_circle_mini.svg, templates/_includes/header.html, templates/components.yaml, templates/registration/login.html
So that we don't need to include custom SVGs in every component.
=> Add SVG icons using Slippers

DEVELOPERS.md
We've discussed this in the team -- let's document it in the developer-facing docs for future reference.
Tangentially related to #2393
=> Document deployment of migrations approaches

templates/_components/form_input_upload.html, templates/_components/registration_form.html, templates/components.yaml, templates/opencodelists/user_create_codelist.html
Closes #2433
Updated the new create a codelist page using Tailwind components. Added new components where needed.
**Before**
**After**
=> Style the create a new codelist page using tailwind

opencodelists/forms.py, templates/opencodelists/user_create_codelist.html
- The codelist owner form field is missing from the page
- Remove unused form helper dependency (spotted this whilst debugging)
=> Fix broken new codelist form for org users

.github/workflows/main.yml, docker/justfile, justfile
=> Run the Python tests with migrations in CI

assets/src/scripts/components/SearchForm.tsx
=> Remove planned boolean search text

assets/src/scripts/__tests__/components/Title.spec.tsx, assets/src/scripts/components/CodelistBuilder.tsx, assets/src/scripts/components/Title.tsx, assets/src/scripts/types.ts, builder/views.py, templates/builder/draft.html
Closes [#2448](https://github.com/opensafely-core/opencodelists/issues/2448)
=> Change draft version text to a badge

justfile, requirements.dev.in, requirements.dev.txt
For details, refer to:
* opensafely-core/repo-template@6d8c0af1ca92e51a34054dbf00262f265588c55d
* jazzband/pip-tools#2176
=> Pip `pip` to 25.0.1

opencodelists/management/commands/setup_local_dev_databases.py, opencodelists/tests/management/commands/test_setup_local_dev_databases.py, pyproject.toml
=> Address unnecessary monkeypatching

assets/src/scripts/__tests__/components/ManagementForm.spec.tsx, assets/src/scripts/components/CodelistBuilder.tsx, assets/src/scripts/components/ManagementForm.tsx, assets/src/styles/base.css, templates/builder/draft.html
=> Move Codelist Builder form buttons to the top-right

assets/src/scripts/__tests__/components/Version.spec.tsx, assets/src/scripts/components/CodelistBuilder.tsx, assets/src/scripts/components/Version.tsx, assets/src/styles/base.css
=> Update the sidebar and versions component styles

opencodelists/management/commands/setup_local_dev_databases.py
Out of context, it's not obvious why a password prompt appears.
=> Add explanation why user sees a password prompt

DEVELOPERS.md
=> Add `just build-dbs-for-local-development` to DEVELOPERS.md

codelists/tests/test_tree_data.py, codelists/tree_data.py, codelists/views/version.py, templates/codelists/version.html
This is the server side part of #2466.
We construct a dictionary server side in the format that will be expected by the React component, and pass it as a json object to the view.
=> Construct tree view object server side and pass to front end as json script

codelists/views/version.py
Steps to test:
* Get a recent local (santiised) db backup restored
* `just run`
* View a dm+d codelist
* Check no 500 errors returned
=> Fix unbound variable error in #2551

codelists/tests/views/test_version.py
This is a test that would have caught the bug fixed with #2566. Fixes #2567
=> Test for non-builder-compatible coding system

static/robots.txt
Closes #2530 
Updates made per [recommendation](https://github.com/opensafely-core/opencodelists/issues/2530#issuecomment-2893715484).
=> Update robots.txt to ignore csv download and login links

assets/src/scripts/__tests__/components/Versions.spec.tsx, assets/src/scripts/__tests__/vitest.setup.js, assets/src/scripts/components/CodelistBuilder.tsx, assets/src/scripts/components/Version.tsx, assets/src/scripts/components/Versions.tsx, assets/src/scripts/types.ts, builder/views.py, opencodelists/tests/functional/conftest.py, templates/codelists/version.html, vite.config.mjs
=> Update version card using existing data

codelists/views/decorators.py
When developing locally, if you try and view a codelist from a coding_system release that is not available locally, you get an unhelpful message like:  "no such table: dmd_amp".  This change gives a more helpful message by saying which database is missing, and looks like this:
=> Improve error message when a database is missing (in dev)

assets/src/scripts/components/TreeTable.tsx
=> Add bottom padding to fix scrollbar hiding content

coding_systems/dmd/coding_system.py, opencodelists/settings.py, opencodelists/templatetags/markdown_filter.py, userdocs/creating-a-codelist-from-a-csv-file.md, userdocs/creating-a-codelist-from-scratch.md
=> Make dm+d builder widely available and document it

codelists/scripts/nhsd_primary_care_refsets.json, codelists/scripts/update_pcd_refsets.py
- config file updated to reflect the latest tag (20250627)
- help text in script updated to reflect actual usage with quoting
- fixed bug with incorrect property name
fixes #2668
=> Changes to config after running the NHS PCD refset update script

codelists/tests/views/test_version_diff.py, codelists/views/version_diff.py
Fixes #2577 
No longer throw a 500 error if more than one codelist is matched. Also try to be a bit clever by:
- if the RHS hash_or_tag resolves to a codelistversion id, then diff with that
- if not then we assume the RHS is a tag and if unique diff with that
- if not unique, but the tag is for a version of the LHS codelist, then diff with that
- if none of the above match we 404. We could show a more helpful error e.g. whether it's the lhs or rhs can't be found - but this is better than it was and fixes the bug where previously a user would get a 500 and we'd have an error appear in sentry
=> Improve codelist diffing by preventing 500 errors and making assumptions if the rhs is a non unique tag

assets/src/scripts/__tests__/builder/codelistbuilder.test.jsx, assets/src/scripts/components/CodelistBuilder.tsx, assets/src/scripts/components/Layout/MetadataTab.tsx
Including the removal of the type information and tests.
See #2771 for the full information about this component.
=> Replace Methodology textarea with new component

assets/src/scripts/components/Cards/SearchForm.tsx, assets/src/scripts/components/Header/ManagementForm.tsx
=> Remove react-bootstrap from more components

codelists/actions.py, codelists/models.py, codelists/tests/test_actions.py, codelists/tests/views/test_codelist_clone.py, codelists/tests/views/test_version.py, codelists/urls.py, codelists/views/__init__.py, codelists/views/codelist_clone.py, templates/codelists/version.html, userdocs/cloning-a-codelist.md, userdocs/views.py
=> Support cloning of codelists

assets/src/styles/feedback-form.css, templates/base-tw.html, templates/codelists/_tab_nav.html, templates/codelists/index.html
Small changes to improve HTML and CSS for users.
=> Various HTML and CSS tiny fixes
