README.md, fabfile.py
This sets `env.use_ssh_config` to `True` and documents SSH config changes one might need to make to be able to deploy.
While working out how to get deploys working from my environment we tried a number of things and various SSH config changes were suggested.  The README change covers what should be the bare minimium to get deploys working.
=> Tell Fabric to explicitly use the user's ssh config

opencodelists/models.py
This fixes a bug where changing an Organisation's name in the admin created a new Organisation since the slug was being regenerated on every save.
=> Only slugify Organisation.slug if it hasn't been set already

.flake8, .github/workflows/main.yml
This sets up GitHub Actions to mirror my preferred CircleCI workflow, specifically a build step, followed by "trivial" checks, finished up with the [potentially] heavier tests step (we could add a deploy step after tests, I'll save that for #49!).
This is my first time really using GitHub Actions so I've used various open source repos (including our own) alongside the docs to build this config.
One thing to take note of - I've used `venv` from the stdlib to allow us to cache the virtualenv in the build step.  However activating that before each run seems a little clunky.
Fixes #54
=> Configure CI

Makefile
Another missed change from #59 
Isort 6.x is recursive by default now!
=> Remove Deprecated Isort Option

requirements.txt
This bumps Pytest to 6.x.  I must have forgotten to do it as part of #59, sorry about that!
=> Bump pytest to 6.x

codelists/actions.py, codelists/forms.py, codelists/tests/factories.py, codelists/tests/test_actions.py, codelists/tests/test_views.py, codelists/urls.py, codelists/views.py, opencodelists/settings.py, opencodelists/tests/factories.py, opencodelists/tests/test_actions.py, opencodelists/urls.py, requirements.in, requirements.txt, static/js/create_codelist.js, templates/codelists/create_codelist.html
This adds the ability to add Sign-Offs and References to Codelists when creating them without having to use the Admin.
It uses two formsets to deal with the multiple Signoff/Reference models related to a Codelist and uses a small amount of Javascript to handle adding more forms.
I've switched the create view over to a Class-based View mainly to separate out the code.  It's based on TemplateView because there's no GCBV for dealing with a form and two formsets but I've mirrored how the various methods are used in [CreateView](http://ccbv.co.uk/projects/Django/3.0/django.views.generic.edit/CreateView/) to maintain consistency with the community (eg conditional creation of Form[Set] instances in `get_context_data`).  I also wanted to showcase a strength of CBVs - in more complicated views a …
=> Add Sign-Offs and References

codelists/forms.py, codelists/models.py, codelists/tests/helpers.py, codelists/tests/test_forms.py, codelists/tests/test_views.py, codelists/urls.py, codelists/views.py, templates/codelists/version.html, templates/codelists/version_create.html, templates/codelists/version_update.html
This validates CSVs uploaded when creating a new CodeList or Version, and when updating an existing Version.  It ensures each row of the CSV has the same number of colmuns as there are headers/columns in the first row.
I chose to split out the Create/Update Version forms into separate views to simplify showing the user errors (I suspect I could have made the modals open on load but I wasn't confident so I went with what I knew!).  So I've cut down the `version` view to no longer handle forms and added `VersionCreate` and `VersionUpdate` to handle them instead.
**Create Version**
**Update Version**
Fixes #48
=> Validate CSVs

codelists/actions.py, codelists/models.py, codelists/tests/test_views.py, codelists/urls.py, codelists/views.py, templates/codelists/version.html
This adds a new button to the LHN controls:
Pops up a modal when clicking this button:
And calls the appropriate action to publish the given Version.
The final commit returns the mutated Version to make redirecting to it cleaner.
Note: the first commit removes some noise from the tests output but is expected to not affect deprecations raised by our code calling deprecated APIs.
Fixes #50
=> Publish Draft Versions

codelists/views.py, templates/codelists/version.html
This lists all versions of a Codelist in the LHN as links.  It marks drafts with a badge and doesn't link the Version currently being viewed.
=> List Versions

.gitignore, Makefile, builder/apps.py, codelists/apps.py, codelists/tests/test_views.py, coding_systems/bnf/apps.py, coding_systems/ctv3/apps.py, coding_systems/readv2/apps.py, coding_systems/snomedct/apps.py, mappings/ctv3sctmap2/apps.py, mappings/rctctv3map/apps.py, pyproject.toml, requirements.in, requirements.txt
This adds test coverage via pytest-cov/coverage.py.
I've opted to skip some modules which I don't think are currently of interest to us, and removed some which coverage pointed out weren't used (autogenerated `apps.py`s).
I've turned on skipping modules with 100% coverage in reports because seeing the list get smaller is a nice positive achievement and gives you fewer things to read!
I've configured it such that `make test` runs coverage (via the `--cov` flags) so we can have coverage by default (and in CI) but a developer can still run pytest without coverage, which is good for tight feedback loops.
=> Add Test Coverage

templates/codelists/version.html
This adds a draft badge to a Codelist title when the current version is a Draft.
We currently show the draft status of versions in the LHN with a badge but given that list is at the bottom of the LHN and the current version is only flagged by "not being a link" (so black text instead of blue) it's not overly obvious.  This aims to make the draft status of a Version immediately obvious to the User.
=> Add draft badge to Codelist title

templates/codelists/version.html
This adds a warning banner on SNOMED Codelists telling users the SNOMED Codelists have been generated.  It links out to the relevant docs for more information.
Blocked by opensafely/documentation#19
Fixes #98
=> Warn SNOMED Codelists are Generated

mappings/ctv3sctmap2/import_data.py, mappings/ctv3sctmap2/models.py
This changes how we import CTV3 -> SNOMED mapping records.  The mapping file includes deactivated maps so instead of only ingesting active maps we need to consider those as well.  Rows in this file with the same Map ID are disambiguated using the Effective Date field (eg we only need to care about the latest version of any Map ID).  This uses an UPSERT query to handle this.
As a nice unintended bonus ingesting is now ~2x fast.
=> Upsert CTV3 -> SNOMED Mappings

builder/actions.py, codelists/actions.py, deploy/gunicorn/conf.py, opencodelists/actions.py, opencodelists/settings.py, pyproject.toml, requirements.in, requirements.txt, services/logging.py
This adds [more] logging to the project via [Structlog](https://www.structlog.org/en/stable/) and it's Django companion package [django-structlog](https://django-structlog.readthedocs.io/en/latest/index.html).
django-structlog binds request and user IDs to the log context allowing us to emit logs from inside our actions and get this kind of output for submitting the Codelist creation form:
```
2020-08-28T07:41:27.826096Z [info     ] request_started                [django_structlog.middlewares.request] ip=127.0.0.1 request=<WSGIRequest: POST '/codelist/test/'> request_id=d3804098-c2c5-4cd3-8e80-b1e3ee2b94a0 user_agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:80.0) Gecko/20100101 Firefox/80.0 user_id=ghickman
2020-08-28T07:41:27.891123Z [info     ] Codelist created …
```
=> Add Logging

codelists/presenters.py, codelists/search.py, codelists/tests/expected_html_tree.html, codelists/tests/factories.py, codelists/tests/test_presenters.py, codelists/tests/test_search.py, codelists/tree_utils.py, codelists/views.py, coding_systems/snomedct/coding_system.py
Notes:
* there's some duplication in setting up database fixtures -- I'll come back to working out the pytesty way to do this another time
* the test for `build_html_tree_highlighting_codes` is only interesting for showing that there are no regressions -- when we tackle #100 we can add proper tests
=> Use hierarchies in more places

codelists/definition.py, codelists/presenters.py, codelists/templatetags/definitions.py, codelists/tests/test_definition.py, codelists/tests/test_presenters.py, codelists/views.py, pyproject.toml, templates/codelists/version.html
This adds the Definition presentation function.  It converts a given Definition instance into a structure (list of dictionaries) ready for display in a template.  The template is now in charge of styling rows of a Definition.
This is a rebuild of #110 on top of @inglesp's new `Hierarchy` object.
=> Add Definition Presenter

opencodelists/settings.py
Sentry [defaults](https://docs.sentry.io/platforms/python/guides/logging/) to picking up logs of `INFO` and above.  django-structlog [logs exceptions](https://github.com/jrobichaud/django-structlog/blob/master/django_structlog/middlewares/request.py#L77-L98) which duplicates the events we already receive.  The events are also ungrouped since the event message contains too many unique parts, giving us a lot of noise.
=> Ignore Request Logging in Sentry

opencodelists/actions.py, opencodelists/forms.py, opencodelists/models.py, opencodelists/settings.py, opencodelists/tests/test_actions.py, opencodelists/tests/test_forms.py, opencodelists/tests/test_views.py, opencodelists/urls.py, opencodelists/views.py, templates/base.html, templates/opencodelists/user_activation_url.html, templates/opencodelists/user_create.html, templates/opencodelists/user_set_password.html
This adds pages to allow the creation of a User without using the Django admin.
Flow TLDR:
1. Admin User creates new User
1. Admin User is shown an Activation URL
1. New User visits Activation URL
1. New User sets password, is logged in
---
There are 3 pages to this flow:
* User creation form
* User Activation URL page
* Set password form
This mirrors the admin form but drops a few fields we don't need (eg date joined).  It doesn't add a password so the new User set it at the end of the flow.  New Users are added as in-active so they're unable to login until they set a password.
This displays some basic User details (name & email) and their activation URL with the expectation that the a Admin who created the User will pass this link on to the New User.  This page is accessible as long as …
=> Add Creating Users

codelists/views.py, templates/codelists/_definition_rows.html, templates/codelists/version.html
This splits up the inactive and active SNOMED Concepts in the Definition tab of a Codelist:
For non-SNOMED definitions it keeps the Definition unchanged:
Fixes #164
=> Split up Active and Inactive SNOMED Concepts

opencodelists/management/commands/import_data.py
This prints out the possible modules for use with the `import_data` command when it fails to import a given module.
=> Suggest Modules when Unknown One Used with Import Data

codelists/management/commands/convert_codelist.py
This is a grab bag of updates to fix `convert_codelist`.
Codelists started tracking versions with the `CodelistVersion` model since we last generated SNOMED codelists.  This updates how we create a Codelist to work with the new model.  It doesn't make use of the `create_codelist` action so we can copy over the `version_str` attribute from the CTV3 Codelist instance.
=> Fix convert_codelist

fabfile.py
This sets both`git-fetch` and `npm install` to quiet mode so deploys don't output progress line-by-line.
=> Quieter Deploys

fabfile.py
This reverts commit d83b469cc24861149b4884343ca775f564b5d3c7.
Disable fabric's use_ssh_config option so automated deploys by EBMBot can work.  With this set to true EBMBot deploys require a password on the server.
This was added to enable deploys from macOS by @ghickman, however we later discovered the issue was macOS not adding SSH keys to the agent by default.
=> Revert "Tell Fabric to explicitly use the user's ssh config"

static/src/js/builder.jsx
This was broken in f106ba39.  Original code only worked because the
first `class="row"` is overridden by the second `class="{className}"`.
Before: 
After:
=> Fix rendering of long rows

static/src/js/TermAndCode.jsx, static/src/js/builder/codelistbuilder.jsx
This pulls the TermAndCode component into a separate file ready to use it to build the Tree tab on the Codelist page.
=> Extract TermAndCode component into a separate file

fabfile.py
This copies the configuration of OpenPrescribing to configure password-less sudo for members of the `fabric` group so we can deploy from ebmbot as the user `ebmbot` (mirror OP again).
I've not tested this yet because I wanted to get a second set of eyes before I run it against production.
Part of #49
=> Deploy as ebmbot

fabfile.py
Openprescribing has multiple deployments (prod and staging).  The `setup_sudo()` function was copied from OP's fabfile.  OP's fabfile differentiates between the two environments using env.app, but we don't have that distinction in opencodelists.  This removes the use of env.app but keeps the same format as OP in case we switch to a two env deployment model.
=> Fix dependency on env.app

fabfile.py
This is take 3 at deploying as `ebmbot`. 😬
I've removed the `setup_sudo()` function as I completely misunderstood what it was doing, and it's not useful to opencodelists.
Instead, I've configured `ebmbot` to have password-less sudo access to `ln` and `systemctl` via `/etc/sudoers`, with this line:
ebmbot	ALL=NOPASSWD:/bin/ln,/bin/systemctl
(TIL: sudo takes the last matching line when checking what permissions a user can have)
The deploy directory has been chown'd to `ebmbot:www-data` (from `www-data:www-data`).
The relevant lines in the fabfile have had `sudo ` prepended instead of calling `sudo()` because that throws up a password prompt regardless of sudoers config.
I've tested this setup locally (my SSH key is authorized for `ebmbot` currently, but I'll remove that once this is merged) …
=> Deploy as Ebmbot… again

builder/urls.py, builder/views.py, coding_systems/snomedct/coding_system.py, static/src/js/builder/codelistbuilder.jsx, static/src/js/builder/index.jsx, templates/builder/codelist.html
This adds a download button to the Codelist builder page which builds a CSV of the codelist (in code,term format).
The button is disabled on codelists with unresolved or conflicted concepts.
Fixes #200
=> Download Codelist from Builder

codelists/hierarchy.py
Hierarchy.from_codes will accept any type of iterable for its `codes` argument.  However if that iterable is a string it will produce a Hierarchy instance with no nodes.  The string is passed to the given `coding_system`'s ancestor/descendant relationships functions which cast it to a list.  In the case of a string this breaks it down into its contained characters, which doesn't return any [correct] results from the database.
Fixes #193
=> Add string-foot-gun guard to Hierarchy.from_codes

builder/views.py, codelists/presenters.py, codelists/tests/test_presenters.py, codelists/tests/test_views.py, codelists/views.py, coding_systems/ctv3/coding_system.py, coding_systems/snomedct/coding_system.py, static/src/js/Code.jsx, static/src/js/DescendantToggle.jsx, static/src/js/Pipes.jsx, static/src/js/Term.jsx, static/src/js/TermAndCode.jsx, static/src/js/builder/codelistbuilder.jsx, static/src/js/tree/Tree.jsx, static/src/js/tree/index.jsx, templates/codelists/version.html, webpack.config.js
This rebuilds the Codelist version page's Tree tab with a modified version of the CodelistBuilder component.  It turned out that only `TermAndCode` was needed from CodelistBuilder so I've left the rest of the sub components where they are.
This also pulls a couple of `tree_tables`-related structures into the coding system specific modules (so we can support CTV3 and SNOMED).  Most notbably, concept codes grouped by type are now generated in the coding system (since CTV3 codes can have more than one group) and passed into `tree_tables`.
These changes brought up the single code Hierarchy edge case (#193), which in turn brought up the three view tests (checking redirects work as expected) that broke due to this work.  I've reduced their scope to only check they are redirecting to the correct …
=> Tree Tab 2.0

builder/tests/test_actions.py, builder/tests/test_views.py, codelists/tests/test_presenters.py, codelists/tests/test_search.py, codelists/tests/test_tree_utils.py, codelists/tests/test_views.py, conftest.py
⚠️ Blocked by #194 ⚠️
This extracts the use of the Tennis Elbow codelist into two fixtures:
* importing the data required for the codelist.
*  constructing a `Codelist` instance from that data.
=> Tennis elbow fixture

coding_systems/bnf/coding_system.py
I'm in the middle of another piece of work that will make lookup_names
redundant.
=> Define bnf.coding_systems.lookup_names

.eslintrc.json, static/src/js/codelist.js
This fixes removing References from the new Codelist form by using the correct event handler for dynamic elements.
Fixes #244
=> Fix Reference Removal

templates/codelists/version.html
* Some SNOMED CT codelists have not been automatically generated
* We're now more confident in the mapping (since #117)
* The codelist description explains that the codelist has been
automatically generated
=> Remove warning banner for SNOMED CT codes

codelists/forms.py, codelists/tests/test_views.py, codelists/views.py
This is in advance of moving the project/name/slug attributes off
Codelist.  Once this has happened, we will no longer be able to use a
ModelForm.
=> Tweak how duplicate codelist names are handled

codelists/views.py
[Sentry](https://sentry.io/organizations/ebm-datalab/issues/1957257441/?project=5248013&query=is%3Aunresolved)
We don't have the `code_to_term`or `code_to_status` lookups for the DM+D Coding System yet, and we're not building a Definition or Tree view for Codelists in that system yet, so don't need those variables yet.
Fixes #273
=> Fix Missing Variables on DM+D Codelists

codelists/tests/test_views.py, codelists/views.py
This fixes the Edit Codelist Form being blank when you edit a Codelist.  It instantiates the CodelistUpdateForm with the necessary values from the existing `Codelist`.
I've removed the `get_form` method now that get/post have diverged enough to remove the abstractions usefulness.
=> Fix Edit Codelist Form

codelists/forms.py, codelists/views.py, static/src/js/codelist.js, templates/codelists/_reference_form.html
This turns on deleting related existing forms in the Reference and SignOff FormSets and modifies the template to retain the choices made by a User.
Fixes #244
=> Fix Deleting Related Forms

deploy/cron/opencodelists
Because we're loading the crontab with `crontab -l`, we don't need the
user.  As it was, the user is being interpreted as the command to run.
=> Fix crontab syntax

codelists/models.py, codelists/views/version.py
These are caused by code_to_term not containing ancestors codes that
match a search term and have been excluded with all their descendants.
This is a problem, because we now show search terms on the main version
page.
Tests to follow, but fix is urgent.
=> Fix 500 errors

codelists/actions.py, codelists/views/version_publish.py
Publishing an already-published version doesn't matter.
This also removes comment added in 94bffe71 about behaviour introduced
in d26f4d68.  As far as I can tell, the comment is incorrect.
Fixes #396.
=> Don't crash if publishing a published version

codelists/models.py, codelists/urls.py, codelists/views/__init__.py, codelists/views/version_dmd_download.py, templates/codelists/version.html
It got lost when we moved CSV downloadings out of the builder
=> Reinstate dm+d download button for BNF codelists

opencodelists/settings.py
Fixes #441.
@ghickman can you think of any other tags that should be allowed?
=> Add <strong> and <em> to allowed markdown tags

deploy/gunicorn/conf.py
For codelists with a lot of searches, exporting the codelist to the
buidler to be edited takes longer than 30s.  This is because we repeat
each search and this can be slow.
A better fix would be add FTS indexes to speed up searching, but for now
bumping the gunicorn timeout will have to do.
=> Bump gunicorn timeout

codelists/views/version.py, templates/codelists/_definition_rows.html
This also removes links to the browser from the definition tab, since we
have not created a browser for ICD-10 (and the existing browsers aren't
very good)
=> Show tree and definition tabs for ICD-10 codelists

static/src/js/common/tree-tables.jsx
This was broken by fa47d6ca.
Users who didn't own the codelist saw:
They now see:
and nothing happens if you click the buttons.
=> Fix tree view

codelists/views/version.py
Certain Y-Codes are missing from the extended CTV3 hierarchy, and so
were not present in code_to_status or code_to_term.
=> Handle codes that are missing from the hierarchy

.pre-commit-config.yaml, codelists/models.py, codelists/tests/test_models.py
This fixes the broken "Download Definition" link for old-style versions.
=> Support codesets for old-style versions

coding_systems/icd10/coding_system.py, coding_systems/icd10/fixtures/README, coding_systems/icd10/fixtures/icd10.json, coding_systems/icd10/management/commands/generate_icd10_hierarchy_fixture.py, coding_systems/icd10/tests.py
Previously, codes at the end of a block (eg M779 in block M75-M77) were
not captured correctly.
=> Fix bug in icd10.code_to_term

codelists/models.py, codelists/tests/test_models.py, codelists/tests/views/test_codelist.py, codelists/views/codelist.py, opencodelists/views/user_create_codelist.py
Previously, the codelist page would redirect to the codelist's latest
version.  However, we don't want to redirect to a version that's
currently being edited.
=> Don't redirect from codelist to builder

codelists/actions.py, opencodelists/tests/fixtures.py
When exporting a codelist with code searches, the codes weren't being
passed correctly, triggering the assert in codelists.search.do_search.
=> Fix export_to_builder

templates/base.html
So that we can track site usage in a privacy-friendly way.
=> Add Plausible Analytics code

pyproject.toml
=> Ignore node_modules in pytest discovery

coding_systems/bnf/import_data.py
Retired BNF codes are removed from the released CSV file, so we cannot
delete and recreate all concepts on import as we do for other coding
systems.
=> Don't delete and recreate BNF concepts on import

codelists/actions.py
This should all be better tested, but doing so requires setting up quite
a bit of extra test data
=> Don't try to cache a hierarchy that doesn't exist

codelists/actions.py, codelists/models.py, codelists/tests/test_actions.py, codelists/tests/test_models.py, codelists/tests/views/test_codelist.py, codelists/tests/views/test_version_delete.py, codelists/urls.py, codelists/views/__init__.py, codelists/views/decorators.py, codelists/views/version_delete.py, opencodelists/tests/fixtures.py, templates/codelists/_are_you_sure_modal.html, templates/codelists/version.html
This PR adds a new "Delete version" button for users who can edit a codelist.
When clicked, the user sees an "are you sure?" modal:
The button is greyed out if the version has already been published, since we do not allow a published version to be changed.
=> Allow versions to be deleted

opencodelists/forms.py, opencodelists/models.py, opencodelists/tests/test_forms.py, opencodelists/tests/views/test_organisations.py, opencodelists/urls.py, opencodelists/views/__init__.py, opencodelists/views/decorators.py, opencodelists/views/organisations.py, templates/base.html, templates/opencodelists/organisation_members.html, templates/opencodelists/user_organisations.html
Fixes #1048 
If a user is a member of one or more organisations, there's now a navbar link to a view that shows a list of the users orgs, with links to the org's codelists and (if the user is an admin for that org) the org's users.
The organisation users page shows a list of users and a minimal form to add a user by email.  It assumes an admin will only add a user who's already signed up to opencodelists.
Error messages are shown if you try to add a user that doesn't exist or is already a member
When a user is successfully added, they're highlighted green in the user table and shown first:
=> Allow organisation admins to add users to organisation

codelists/models.py, codelists/tests/test_models.py, codelists/tests/views/test_index.py, codelists/views/index.py
Codelists with no published versions are currently being returned in
search results, but these are not accessible to anyone outside of the
OpenSafely organisation.
An example is given in [Github Issue #1111](https://github.com/opensafely-core/opencodelists/issues/1111)
=> Display only codelists with a published version

builder/actions.py, builder/tests/test_actions.py
Fixes #786 #870 #668 (all duplicates)
Duplicate searches were previously attempting to recreate the search, and raising an IntegrityError.  If a user searches for the same term again, we now return the previously created search.
=> Handle duplicate searches

builder/decorators.py, builder/tests/test_views.py, builder/views.py, codelists/models.py
Discarding a draft was resulting in a 500 error to the user, although the draft was successfully deleted.
In the case where a draft was the sole version for a codelist, the codelist itself was also deleted, and the error was caused by an attempt to redirect to the non-existed codelist URL (`Handle.DoesNotExist` error)
Fixes #867 
In the case where there were multiple drafts, the error was caused by an attempt to cache the hierarchy on a discarded version (`CodelistVersion.cached_hierarchy.RelatedObjectDoesNotExist`)
Fixes #868
Fixes #922
=> Fix bugs with discarding drafts

static/src/js/builder/codelistbuilder.jsx, templates/codelists/version.html
Fixes #1038 
Wrap long codelist IDs and allow words to break if they need to, on both builder and codelist pages
=> Wrap long codelist IDs

opencodelists/settings.py
The better solution may be to migrate to postgres, but for now, this reduces "database is locked" errors on long queries (e.g. searching for codes starting with just one or two characters.
=> Increase database timeout to minimise 'database is locked' errors

builder/tests/test_views.py, builder/views.py
A (non "code:"-prefixed) search term is converted to a slug using django's `slugify` method, and forms part of the URL for the search.  If a user searches for a term that results in an empty slug after conversion, this ends up with a Search that has an invalid URL.  The search view attempts to redirect to the invalid URL, and after that the entire codelist page is broken, because the template tries to render the invalid URL.
Mostly, we'd expect that users aren't going to search for random strings of punctuation that result in empty slugs.  However, they could enter a single character and hit search by mistake, or as @Jongmassey found out, try to return all codes by entering `*` (instead of `code:*`)
=> Reject search terms that result in empty slugs

codelists/list_utils.py, codelists/tests/views/test_index.py, codelists/urls.py, codelists/views/index.py, templates/codelists/_search_form.html, templates/codelists/index.html, templates/codelists/under_review_index.html, templates/opencodelists/user_organisations.html
Now that organisation members have a "My organisations" page, we can give them a list of both published and under-review codelists.  This means that any organisation-owned under-review codelists that don't have authors (either because they predate the author field, or because they were uploaded via the API) can be accessed easily by members of that organisation.
=> Organisation members can see organisation-owned under-review codelists

codelists/models.py, codelists/tests/test_models.py, static/src/js/builder/codelistbuilder.jsx, templates/opencodelists/this_user.html
Fixes #1127 
- Show versions on the builder page
The code for this was there already, but was only showing up if a draft had searches.
- Use latest published version URLs on user's codelists page
The `Codelist.get_absolute_url` returns the latest visible version for that user, but when a codelist has both a published version and a version in draft or under review, we expect the link under "My codelists" to show the latest published version, and the link under "My codelists under review/My drafts" to show the relevant unpublished version.
=> Show versions on builder page, and latest published version on user codelists page

DEPLOY.md
Trying to upload a large (i.e. 3Mb) CSV file was resulting in a 413 error, which was fixed by upping the nginx `client-max-body-size` setting.  This PR documents how to do that.
=> Add dokku nginx configuration to deploy docs

templates/base.html
...to include Bennett and Oxford links.
This also makes the footer stick to the bottom of the screen, when the main content does not fill the screen height.
=> Update footer styles and links

codelists/actions.py, opencodelists/tests/views/test_user_create_codelist.py, opencodelists/views/user_create_codelist.py
If a user creates a codelist by uploading a CSV, it is automatically published (and doesn't go via the builder).  This PR ensures that the user who uploads the CSV is recorded as its author.
=> Record author for codelists created by uploading csv

codelists/views/version.py
Large codelists take a really long time to load in the version view; e.g. [this one ](https://www.opencodelists.org/codelist/user/rebkwok/test-large-csv/2227f362/) will load, but it takes about 1.5 mins (after some fiddling with gunicorn settings to let it wait longer before timing out).  @Jongmassey attempted to upload the [same codelist](https://www.opencodelists.org/codelist/user/jon_massey/ali_test_non-ab/3b376697/) and that one runs into a cloudflare timeout.
The slowest part of this view turned out to be a dictionary comprehension; with the version in this PR, that codelist takes about 5s to load for me locally, vs 1.5 mins.  This is just an interim fix to get it to load though - displaying the full list or the tree works, but is still very slow, and doesn't show any sort of helpful …
=> Refactor slow dictionary comprehension in version view

userdocs/creating-a-codelist-from-a-csv-file.md
Adds instructions for uploading an opcs-4 codelist and moves some existing info from main documentation. This accompanies opensafely/documentation#592.
=> Add notes on uploading OPCS-4 codelists

codelists/codeset.py, codelists/management/commands/update_draft.py, codelists/tests/test_api.py, codelists/tests/test_commands.py, coding_systems/snomedct/fixtures/enthesopathy-of-elbow-region-plus-tennis-toe.csv, opencodelists/tests/fixtures.py
Fixes https://github.com/opensafely-core/opencodelists/issues/1275
When a coding system is updated, it can result in a mismatch between the draft version's hierarchy, and its codeset's code_to_status dict (e.g. there are new codes that are implicitly included by others, codes that have swtiched places in the hierarchy, codes that have been replaced).
This PR is an interim strategy to allow us to fix up drafts that were created prior to a coding system update, but defers the full implementation for future us.
- Adds a management command that can be run manually to update a draft
- Modifications to the main codebase are as minimal as possible.  The only addition is `Codeset.reapply_statuses`, and this is only called from the management command.  This means there's some duplicated code in …
=> Add a manage command to fix a draft version after a coding system update

static/src/js/builder/codelistbuilder.jsx
For an ICD-10 codelist, users can search for codes that start with a prefix, using a wildcard (`code:xyz*`).  For other conding systems, this doesn't make sense (see [this slack thread](https://bennettoxford.slack.com/archives/C63UXGB8E/p1659525543519349)) and isn't implemented, but the help text under the search field still refers to it, which is confusing, especially as it will never return anything (i.e. for a BNF codelist, `code:01` returns  lots of results (all, `code:01*` returns nothing).  This PR just removes the reference to "startswith" searches for non-ICD-10 codelists.
=> Include wildcard search in helptext for ICD-10 only

codelists/hierarchy.py, coding_systems/ctv3/README, coding_systems/snomedct/README, mappings/ctv3sctmap2/import_data.py, mappings/ctv3sctmap2/models.py, mappings/ctv3sctmap2/tests/test_mappers.py, opencodelists/tests/fixtures.py, userdocs/creating-a-codelist-from-a-csv-file.md, userdocs/creating-a-codelist-from-scratch.md, userdocs/what-is-a-codelist.md
Relates to https://github.com/opensafely/documentation/issues/910
Most existing references use "SNOMED CT" correctly.
=> Use "SNOMED CT" more consistently

codelists/actions.py, codelists/management/commands/update_draft.py, codelists/views/version.py, coding_systems/bnf/coding_system.py, coding_systems/bnf/tests/test_coding_system.py, coding_systems/ctv3/coding_system.py, coding_systems/ctv3/tests/test_coding_system.py, coding_systems/icd10/coding_system.py, coding_systems/icd10/tests/test_coding_system.py, coding_systems/snomedct/coding_system.py, coding_systems/snomedct/tests/test_coding_system.py, opencodelists/forms.py
Fixes #1333 
There are a few codelist versions that contain codes that aren't found in the coding system (see [this comment](https://github.com/opensafely-core/opencodelists/issues/1333#issuecomment-1209598028) for details).  This can happen for old codelists that were created by uploading CSV data directly (not via the "create a codelist" form, which turns CSV data into code objects and raises errors if any codes are invalid). It could potentially also happen if a coding system update removed a code.
The code already allows for codelists that have unknown codes in this function, which is used to show the table on the "Full List" tab: 
https://github.com/opensafely-core/opencodelists/blob/43c1510fe9ef62e1298d0582e98290e9cced7f21/codelists/models.py#L449
(New style codelists generate the …
=> Display codelist versions that have unknown codes 

mappings/bnfdmd/import_data.py
A couple of other defensive measures are no longer necessary, but have
been changed to asserts.
=> Fix bnfdmd importer to handle empty spreadsheet cells

builder/views.py, codelists/tests/test_api.py, codelists/tests/views/test_index.py, codelists/tests/views/test_version_diff.py, codelists/views/version_diff.py, coding_systems/dmd/coding_system.py, coding_systems/dmd/fixtures/asthma-medication-alt-headers.csv, coding_systems/dmd/fixtures/asthma-medication-refill.csv, coding_systems/dmd/fixtures/asthma-medication.csv, coding_systems/dmd/fixtures/asthma-medication.json, coding_systems/dmd/tests/test_coding_system.py, opencodelists/tests/fixtures.py
Fixes #1387
We have a view already for diffing codelists, e.g. https://www.opencodelists.org/codelist/primis-covid19-vacc-uptake/bmi_stage/v1.2/diff/08641331/
This currently only works for codelist versions that have code objects - i.e. new-style codelists that have been imported from CSV using the "create a codelist" form, or built using searches in the codelist builder.  dm+d codelists aren't currently buildable via the builder, so only contain uploaded data in the `CodelistVersion.csv_data` field.  To complicate things further, dm+d uploaded csv data may have different headers, so we have to figure out which column contains the code.  
This PR updates the codelist diff view to support dm+d codelists.  This involves:
1) retrieving codes from the uploaded csv_data for a dm+d codelist …
=> Support diffing dm+d codelists

coding_systems/versioning/management/commands/migrate_coding_system.py, coding_systems/versioning/models.py, coding_systems/versioning/tests/test_management.py, opencodelists/settings.py
With PR #1397, each coding systems will be migrated to use a separate database.  Whenever we import new data, that will also be imported to a separate database so that we can maintain historic versions of coding systems.  If we keep the database files in the same location as the main db, it will quickly litter the filesystem with sqlite files (in the base directory for local development, and in the /storage/ directory in prod).  This PR just makes each coding system's db files live in a separate subdirectory.
=> Put the coding system database files in separate directories

CHECKS
The last deploy failed before it finished running migrations (it has some slow ones to do)
https://github.com/opensafely-core/opencodelists/actions/runs/3429120087/jobs/5714352203#step:9:105
=> Make dokku wait longer

coding_systems/snomedct/ecl_parser.py, coding_systems/snomedct/tests/test_ecl_parser.py, pyproject.toml
The parser utils for the SNOMED CT Expression Constraint Language are a set of tools that we[ download](https://github.com/opensafely-core/opencodelists/blob/main/coding_systems/snomedct/parser_utils/README).  We have a small ecl_parser module that makes use of them, but the tools themselves are third-party shouldn't need to be included in our overall coverage.
This PR adds a couple more tests for the ecl_parser and omits the third party toold from coverage.
=> Skip coverage for third party ECL parser utils

coding_systems/versioning/models.py, coding_systems/versioning/tests/test_database_routing.py, coding_systems/versioning/tests/test_models.py, opencodelists/db_utils.py
A CodingSystemRelease is associated with a database_alias, which is expected to be in the format `<coding_system>_<release_name>_<valid_from>`.  The database alias is set on model save, however, it was previously possible for it to be specified on the model as something different.  We don't want to allow that, as it's used to create the release's database file, and it's used by the database router (which expects it to be in this format).  
This PR also adds a test to complete the test coverage on the database router.
=> Ensure the format of database_alias always follows the expected pattern

codelists/forms.py, codelists/models.py, codelists/tests/test_forms.py, codelists/tests/views/test_codelist_create.py, codelists/tests/views/test_version_upload.py, codelists/views/version_upload.py, opencodelists/forms.py
Fixes #1388 
Old-style CSV data can be uploaded at `/codelist/<user/username or org>add`; this adds the uploaded csv data to `CodelistVersion.csv_data` rather than generating `CodeObj` instances for each code.  CodelistVersions without hierarchies in OpenCodelists (i.e. dm+d, OPCS-4, ReadV2) can only be uploaded via this method, but all coding systems are allowed.  It's mainly used for uploading dm+d codelists now.  No validation was being done on the uploaded data, beyond checking that headers don't contain whitespace, and all rows have the expected number of columns.
This PR adds validation of the CSV data, by checking that all codes can be looked up in the latest version of the coding system, in the same way that the normal "create a codelist" form does (reports the number of invalid …
=> Validate old-style CSV uploads

coding_systems/dmd/import_data.py, mappings/bnfdmd/README, mappings/bnfdmd/import_data.py
Some fixes for dm+d imports, needed to address #1463 
1) dm+d data downloads are a zip file; in the most recent downloads, one of the zip's subfolders is now also zipped, so the importer needs to unzip that too.
2) bnf to dmd mappings are released monthly; I'm not sure when the mappings were last updated in opencodelists, but the import_data command errored due to a unique constraint, because it was trying to bulk import Mapping objects without deleting the existing ones first.  Since we only use the most recent dm+d release currently (both for converting bnf codelists to dm+d, and for uploading dm+d codelists), we want the mapping to also be the most recent.  Mappings might change between releases, so i think it's safest to delete them all and start from a clean slate with the new …
=> Bugfixes for dm+d and bnfdmd mapping imports

coding_systems/bnf/README, coding_systems/ctv3/README, coding_systems/dmd/README, coding_systems/icd10/README, coding_systems/snomedct/README, opencodelists/management/commands/import_coding_system_data.py
After importing new coding system data into the prod dokku app, we need to restart the app in order for the new database connections to be picked up
=> Add note to restart app after importing data to coding system READMEs

codelists/tests/test_forms.py, opencodelists/forms.py
We have a couple of coding systems that we don't maintain data for, and can't validate (OPCS4 and ReadV2) - this just makes the CSV upload skip code validation for those.
=> Skip CSV validation for coding systems without data to validate

coding_systems/base/import_data_utils.py, coding_systems/ctv3/import_data.py
The CTV3 Hierarchy download from TPP is big, and is failing to import in production.  I'm speculating that this is because `bulk_create` turns the entire thing into a list and evaluates the generator that's loading the records from the CSV file, and that batching the `bulk_create` operations will avoid memory issues.  Sqlite only allows a max 999 inserts at a time, so django would already be batching the queries in `bulk_create`, and we don't care about the returned list of objects.
=> Batch ctv3 imports

opencodelists/management/commands/import_coding_system_data.py
Make sure we're passing valid-from as a date rather than a datetime.  This was causing imports of specific dm+d versions (as opposed to just the latest version) to fail when checking dates from retrieved releases against the supplied valid-from date
https://github.com/opensafely-core/opencodelists/blob/main/coding_systems/dmd/import_data.py#L59
=> fix: Ensure valid-from in management commands is a date

userdocs/creating-a-codelist-from-a-csv-file.md
The main codelist creation page doesn't let you upload dm+d or OPCS-4;  there's an alternative CSV upload page that's documented, but only for OPCS-4 at the moment.  This updates it to refer to dm+d as well, and also fixes the instruction for constructing the URL
=> Update instructions for uploading opcs4 and dm+d uploads

codelists/actions.py, codelists/tests/views/test_version_create.py, codelists/views/version_create.py, templates/codelists/version.html
We don't yet have a way for users to select a coding system release when they create a codelist or a new version of an existing codelist.  The intention was for those to continue to work as they did before - i.e. they use the most recent release.  This makes creating a new version from a codelist actually do that, rather than using the version that the original codelist was created with.
=> Use most recent coding system release for new versions

.flake8
As https://github.com/opensafely-core/databuilder/commit/ec1f8316face0b7b90d70db29eb94b0155c5b0f6
Without these changes, this will eventually break from flake8==6.0.0 as flake8 no longer silently ignores malformed lines.
=> Correct `.flake8` configuration

coding_systems/versioning/tests/test_views.py, coding_systems/versioning/urls.py, coding_systems/versioning/views.py, opencodelists/urls.py, templates/versioning/latest_releases.html
Adds a page at /coding-systems/latest-releases to show the latest release of each coding system (with valid from and import timestamp).  
Currently this is really just for convenience so we can check what the latest imports are and easily see whether a coding system needs to be updated, so it isn't linked from anywhere else.
=> Add a view to show latest release for each coding system

codelists/models.py, codelists/tests/test_models.py, codelists/tests/views/test_version_download.py, codelists/views/version_download.py
Fixes #1522 
By default, downloading a CSV (for an old-style codelist) just downloads the exact same data that was uploaded.  
(For a new-style codelist - one created with the form at `/users/<username>/new-codelist/` - the download builds the CSV data from the codelists codes, and always contains 2 columns headed "code" and "term".)
Old-style codelists may in the past have been uploaded with a variety of column headings.  This PR adds an optional query param `?fixed-headers` to the download URL which downloads all codelist versions, including old-style ones, with "code" and "term" columns only, with those headings.
e.g. /codelist/codelist/user/rebkwok/test/04e24d7d/download.csv?fixed-headers
This is so OSI can retrieve a codelist CSV with deterministic column headings.
=> Download CSVs with fixed headers

codelists/api.py, codelists/tests/test_api.py
Fixes #1540 
updates /api/v1/codelist endpont to:
- return organisation codelists only by default
- include user codelists if the "?include-users" query param is used
- if an owner is specified (by calling e.g. /api/v1/codelist/opensafely/), ignore any codelists for which that owner is not the current owner (previously we were getting the one codelist back in the response which used to belong to opensafely and now belongs to a user)
- Add an `updated_date` for each codelist version returned. (Note this isn't "published_date" for published versions, although in general it SHOULD date of publication, because from the interface, there's no way to modify a published version.  However, since it's an autoadd field, it'll get updated on any save, with or without changes, so it could potentially …
=> API updates to support OSI

codelists/models.py, codelists/tests/views/test_version_diff.py, codelists/views/version_diff.py
If a code from a codelist version is not found in the coding system data, its term is returned as "Unknown" in the codelist diff view.  However, some codelist versions, including all dm+d ones, are uploaded from (old-style) CSV data, which keeps a record of the literal csv data, rather than coverting it into `CodeObj` objects via the coding system data. As long as we can determine a term column from the original CSV data, we can report the term that was uploaded with the original data.  Some dm+d CSV uploads also include the dm+d type, so if we have that, we can report it too.
Terms for unknown codes are prefixed with "[Unknown]" to inform the user that the term isn't found in the coding system.
Fixes #1555
=> Show terms from original CSV data in diff view if unknown in coding system

codelists/actions.py, codelists/management/commands/create_and_update_draft.py, codelists/management/commands/update_draft.py, codelists/tests/test_actions.py, codelists/tests/test_commands.py, codelists/tests/views/test_version_create.py, codelists/views/version_create.py
This allows us to manually create a new draft that can't be generated via the builder UI.
See https://bennettoxford.slack.com/archives/C03FB777L1M/p1684936597607569
We currently can't create a new draft if the coding system has changed since the original version was created, such that the searches on the original version now bring back new codes, which will be given unknown ("?") status.
We already had an `update_draft` management command, which would fix up an **existing** draft which had fallen behind the coding system (i.e. the draft was created in the past, and the coding system had been updated since).  We can use the same mechanism to create a new draft with the current coding system release, and update any unknown codes on it.
Note that we still don't want to do this automatically, …
=> Management command to create and update a draft for use in the builder

codelists/actions.py, codelists/management/commands/create_and_update_draft.py, codelists/management/commands/update_draft.py, codelists/tests/test_actions.py, codelists/tests/test_commands.py, codelists/tests/views/test_version_create.py, codelists/views/version_create.py, opencodelists/tests/fixtures.py
Fixes #1563 
When we create a new draft from an existing version, it reruns the searches, and if any codes are returned with unknown (?) status, it raises an error (because - according to a comment - the frontend can't deal with codes of unknown status if an ancestor code is included/excluded) and tells the user to contact tech-support.  However, in fact, the frontend can deal with these just fine.
What the frontend can't deal with is new codes that have an ancestor code that is included/excluded, and which have no CodeObj created on the draft. We now check for those in `export_to_builder` and create them with no specific status (so they will be assigned unknown).  We don't do any automatic assigning of statuses based on the parent codes, we just return the draft to the user with …
=> Create new draft versions with CodeObj instances for unknown codes

codelists/migrations/0020_auto_20201119_0932.py, coding_systems/versioning/tests/test_models.py, opencodelists/settings.py, requirements.prod.txt
- Adds the new STORAGES setting
- Add a test to reassure me that the [changes to update_or_create](https://docs.djangoproject.com/en/4.2/releases/4.2/#setting-update-fields-in-model-save-may-now-be-required) in 4.2 aren't a problem
- minor fixes to get rid of new deprecation warnings
=> Upgrade to Django 4.2

deploy/bin/import_latest_dmd.sh, deploy/bin/import_latest_snomedct.sh
A few weeks ago, dm+d automated import started to fail, but we didn't notice for a while because the failure notifications were posted into #tech-noise.  This makes them call tech-support for investigation.
Note that snomed isn't released on a very regular schedule (it's around every 2 months, but sometimes has interim minor releases), so we try to import weekly, but we expect it to fail about 9/10 times, when it doesn't find a new release to import. We can probably fix that in the code, but for now, just notify tech support with the urls to check.
=> Call tech-support in slack for failed automated imports

deploy/bin/import_latest_dmd_cronfile, deploy/bin/import_latest_release.sh, deploy/bin/import_latest_snomedct_cronfile
Change slack notification to post directly to #team-data instead of tech support.
=> Notify data team directly for dmd and snomedct import failures

codelists/api.py, codelists/models.py, codelists/tests/views/test_version_download.py, codelists/views/version_download.py, mappings/dmdvmpprevmap/mappers.py, mappings/dmdvmpprevmap/tests/test_mappers.py
Includes mapped VMPs in dm+d CSV downloads by default (they can be omitted with a query parameter flag ?omit-mapped-vmps)
This means that running `opensafely codelists update` on a study will download CSVs that include mapped VMPs (and  note in the downloaded CSV which VMP they map to).  The study will have codelists with mapped VMPs that it can use, without modifying CSV files that have already downloaded (which would cause OS CLI's codelist checks to fail), and we don't have to create new dm+d versions that circumvent the current coding system validation.
Example download from the opiods study that currently having problems with mapped VMPs:
[opensafely-opioid-containing-medicines-parenteral-excluding-drugs-for-substance-misuse-dmd.csv](https://github.com/opensafely-core/opencodelists/fi …
=> Include mapped VMPs in dm+d CSV downloads

codelists/models.py, codelists/tests/views/test_version_download.py
We need the order of mapped VMP codes to be consistent on each download for any checks on whether codelists have changed.
=> Sort mapped VMPs in download view

codelists/models.py, codelists/tests/views/test_version_download.py
For dm+d codelists, we now default to including mapped VMPs in CSV downloads. In order to do that, we need to use the code that downloads with fixed headers (i.e. two columns, headed 'code' and 'term'), so for dm+d codelists ONLY, we need toignore the default value of fixed_headers (False).
=> Respect fixed_headers for non-dm+d codelist downloads

codelists/models.py, codelists/tests/views/test_version_download.py
#1696 fixed the issue for past VMP mappings more than one step away from codes in the codelist being downloaded; this fixes the issue for future ones too :facepalm: 
I'm not entirely happy with how the description ends up - every mapped code that's previous to a VMP in the codelist gets labelled as "previous to" the codelist code (even if it's in a chain of mappings, so not immediately previous), whereas every future mapped code gets labelled as "subsequent to" the code it's actually mapped to.  However, all the right codes end up in the codelist, and the description notes were only ever a nice-to-have, so I don't think it's worth spending a lot of time trying to make it work better (right now, at least).
=> Make dmd VMP mappings handle multiple future mappings

codelists/api.py, codelists/api_urls.py, codelists/models.py, codelists/tests/test_api.py
Fixes #1702 
See also https://github.com/orgs/opensafely-core/projects/13/views/1?pane=issue&itemId=42536167
This endpoint may be called from opensafely-cli or from job-server. It takes as POST parameters the content of a study repo's codelists.txt file (specifying the codelists that are to be used in the study), and a manifest (codelists.json) file, which is generated when `opensafely codelists update` is run. It checks that the hashed codelist data in the manifest file matches the content of the current codelist versions, if they were to be downloaded again.
This is specifically intended to deal with dm+d codelists, which may change after they're downloaded into a study repo due to mapped VMPs.
Note opensafely-cli already has a codelists check command, which checks that the manifest …
=> Add an API endpoint to check codelists from study repos

codelists/models.py, codelists/tests/test_api.py
This reproduces the method used by opensafely-cli to hash codelist CSV files downloaded into study repos from OpenCodelists.
=> Replace line endings before hashing CSV data

codelists/api.py, codelists/tests/test_api.py
We need to match codelists by tag or hash; tag doesn't go through any cleaning, so it can technically be any string, including random characters and forward slashes. We're identifying whether a codelist in a codelists.txt file is valid by using forward slashes as a delimiter between user-or-org/codelist-slug/tag-or-hash, so we need to exclude forward slashes from the allowed characters for the tag-or-hash part of the regex. This is fine, since any codelist version that was created with forward slashes in the tag would have a broken url anyway.
=> Fix the regex used to match codelists in codelists_check

codelists/api.py, codelists/models.py, codelists/tests/views/test_version_download.py, mappings/dmdvmpprevmap/mappers.py, mappings/dmdvmpprevmap/tests/test_mappers.py
Discovered another small bug in how the mapped VMP descriptions were produced, and realised that the previous code was ridiculously overcomplicated.  The first commit refactors the way the mapped-VMP descriptions are generated, the second one removed the extra code that was only there for the overcomplicated previous version.
=> Refactor csv download code for mapped VMPs

deploy/bin/import_latest_release.sh
dm+d imports have started failing again every so often.  So far a re-run of the import command has worked. This just updates the slack message with a reminder of what the required command is to that (have checked with a webhook on a test slack workspace that the message can be interpreted and formatted OK).
=> Add instructions on how to rerun a failed coding system import

codelists/scripts/import_codelists_from_xlsx.py
API calls to https://opensafely.org are redirected to https://www.opensafely.org which results in 405s from endpoints that only allow POST
=> Add note about prod host for import_codelists_from_xlsx script

codelists/api.py, codelists/models.py, codelists/tests/test_api.py, codelists/tests/views/test_version_download.py
CSV downloads for dm+d codelists now map in any previous or subsequent VMPs. As part of that change, the downloads also changed to use standardised fixed headers ("code" and "term"). However, this means that any old dmd download no longer matches the data that would be downloaded today - even if no VMPs were required to be mapped in.
In addition, if a user updates their study codelists, their study/dataset definitions that referred to a named code column (often "dmd_id" for codelists created from BNF conversions) will no longer work, and the user would have to update all their `codelist_from_csv(column="dmd_id")` calls to use `codelist_from_csv(column="code")` instead.
This PR address these things by:
1) Including an additional column in the dm+d CSV downloads which is a duplicate of the …
=> Check dm+d codelists against possible previous versions of downloaded CSVs

templates/codelists/_about_tab.html, templates/codelists/version.html
Add alternative download options in the UI for dm+d codelists, to download the original CSV data, or data with mapped VMPs. Also adds a note about mapped VMPs and link to docs page.
=> CSV download options for dm+d codelists

templates/codelists/_full_list_tab.html, templates/codelists/version.html
By undownloadable, we mean that it doesn't have an identifiable code
column header in the csv_data field, so it's undownloadable for OSI, and
also can't be used to retrieve mapped VMPs. We now validate codelists created
by csv upload, so this only applies to particularly old codelists. These
can still be downloaded in their original format.
e.g. https://opencodelists.org/codelist/opensafely/methotrexate-oral/738b5e12/#full-list
contains codes in a "VMP" column, which is not one of the allowed code headers.
This will prevent users hitting the assertion error e.g.:
https://ebm-datalab.sentry.io/issues/4628776626/?alert_rule_id=1877862&alert_type=issue&notification_uuid=788df5b5-7b73-4483-b635-ebc0cab896a6&project=5248013&referrer=slack
Also adds a footnote on the "full list" tab, [as …
=> Disable the download-with-vmp button if a dm+d codelist is undownloadable

codelists/models.py, codelists/tests/test_api.py, codelists/tests/test_models.py, codelists/tests/views/test_version_download.py, codelists/views/version_dmd_download.py, codelists/views/version_download.py
Fixes #1760 
dm+d downloads were previously downloading with just a code and term column by default, and mapping in any previous/subsequent VMPs that they needed to (with a note in the term column to describe where they were mapped from/to). However, in some cases, a study uses other columns from the original uploaded csv data - particularly category columns. OpenCodelists doesn't know or care about category columns, so we just add in any other original columns to the csv download.
=> Include original csv data columns with default dm+d downloads

docker/Dockerfile
Update uid/gid to match the one set in dokku3 provisioning.
See https://github.com/ebmdatalab/sysadmin/pull/308
=> Update docker user/group id

codelists/tests/test_api.py, codelists/tests/views/test_index.py, codelists/tests/views/test_version_diff.py, codelists/views/version_diff.py, coding_systems/base/coding_system_base.py, coding_systems/base/tests/test_coding_system.py, coding_systems/versioning/fixtures/coding_system_releases.json, opencodelists/tests/fixtures.py
Fixes the [sentry error](https://ebm-datalab.sentry.io/issues/4739425662/?alert_rule_id=1877862&alert_type=issue&notification_uuid=186c6ca7-93fc-432c-8355-cc98d87ea9fe&project=5248013&referrer=slack) here.
At the same time (and so that the bugfix can be tested), adds a "null" coding system codelist fixture, and allows diffs of codelists from all non-hierarchical coding systems (not just dm+d)
=> Bugfix and updated to version diffs

.github/workflows/main.yml
This was correct in the smoketest run during tests, but not during deploy.
=> Fix docker container ref in smoketest

.gitignore, docker/docker-compose.yaml, docker/justfile
In actual prod, we mount a volume that is owned by the non-root docker user. In the prod smoketest, we need to make sure that the volume mounted in is also owned by the non-root user. The db doesn't exist at this stage, so it will be created in the test.
=> Ensure prod smoketest can create/read db file

deploy/bin/import_latest_dmd_cronfile, deploy/bin/import_latest_release.sh, deploy/bin/import_latest_snomedct_cronfile
Update webhooks to post failure notifications to the team responsible.
The actual webhook is an environment variable specified in the cronfile on dokku3; I've changed the name of the variable so it doesn't reference the specific team, so that in the event that we change teams/team names again, we just need to update the env var content.
See https://github.com/ebmdatalab/sysadmin/issues/313
=> Update slack webhook for data import failures

DEPLOY.md, DEVELOPERS.md, codelists/scripts/README, codelists/scripts/import_codelists_from_xlsx.py, codelists/tests/test_import_codelists_from_xlsx.py
Update the xlsx import script:
- add some better error messaging
- add an extra config option so the import can be limited to specific named codelists
- move documentation from the script to a README and link to it from DEVELOPERS.md
This script was initially created for the PINCER codelists, using the format of their xlsx file. Updates are based on latest request to update PRIMIS vaccination uptake reporting codelists, which take a similar form (#1771)
=> Updates to xlsx codelist imports

deploy/bin/import_latest_release.sh, opencodelists/management/commands/import_latest_data.py
Fixes some annoyances with the logging for dm+d and snomed imports that run overnight.
1) we were getting horrible escape sequences in the output. I couldn't figure out why - structlog's formatter has colour fomatting turned off on prod, so it doesn't seem to be that. Some was definitely from the output of django commands, which are supposed to also turn off colour formatting when redirecting to a file, but didn't seem to. This now pipes it through sed to remove them.
2) If dm+d imports fail, which they do every so often, it's usually because it was killed for some reason, and it's (so far) always just needed re-run. We helpfully post the command you need to rerun it to slack along with the failure message, but we weren't reporting the values for "release name" and "valid from" early …
=> Improve logging for automated imports

.github/workflows/main.yml
This is an attempt to fix the currently failing "Create Sentry release" step.
=> Set fetch depth in deploy job 

opencodelists/settings.py
Several users have experienced `OperationalError`s because the database has been locked. Whilst these errors relate to the builder, it's proving hard to recreate them locally. It's not the case, for example, that making many updates to a single codelist in a short space of time locks the database.
Finding the route cause of the errors will take time. However, given that the error has occurred 55 times in the last 30 days, increasing the timeout from 30s to 45s and monitoring the errors seems reasonable.
Thanks to @emprestige for reporting the errors in the first instance.
Closes #1811
=> Increase timeout to 45s

DEVELOPERS.md
This should be done sparingly for the reasons given in the commit, but is a process we have carried out on occasion.
=> Add information on deleting published codelists

templates/base.html, templates/codelists/index.html, templates/codelists/version.html
- Use lite-yt-embed to show home page videos 
- Replace cdn.datatables.net with cdnjs.cloudflare.com
- Move datatables assets to version template (the only place they are used)
=> Update CDN linked assets

codelists/api.py, codelists/tests/test_api.py
Add codelist metadata to API response
This adds description, methodology, and references properties (codelist metadata) to a response, following a request with the appropriate query parameters. The following example takes roughly 4s to execute locally.
http://localhost:7000/api/v1/codelist/?description&methodology&references
Closes #1991
Acceptance criteria:
Closes #1991
=> Add codelist metadata to API response

requirements.dev.txt, requirements.prod.txt
Closes:
* https://github.com/opensafely-core/opencodelists/security/dependabot/92
* https://github.com/opensafely-core/opencodelists/security/dependabot/93
=> Bump certifi from 2023.7.22 to 2024.7.4

requirements.dev.txt, requirements.prod.txt
A vulnerability in the package_index module of pypa/setuptools versions up to 69.1.1 allows for remote code execution via its download functions. These functions, which are used to download packages from URLs provided by users or retrieved from package index servers, are susceptible to code injection. If these functions are exposed to user-controlled inputs, such as package URLs, they can execute arbitrary commands on the system. The issue is fixed in version 70.0.
Fixes https://github.com/opensafely-core/opencodelists/security/dependabot/100
=> Bump setuptools from 69.0.3 to 70.3.0

DEVELOPERS.md, dotenv-sample, opencodelists/settings.py, opencodelists/urls.py, requirements.dev.in, requirements.dev.txt, requirements.prod.in, requirements.prod.txt
and rename `DDT_ENABLED` environment variable to `DJANGO_DEBUG_TOOLBAR`, matching our other Django projects.
Closes #2023
=> Make django-debug-toolbar a development dependency

DEVELOPERS.md
In OpenCodelists, backups are JSON fixtures rather than SQL dumps. To restore from a backup, we must remember to remove the existing database and migrate, and *then* to load the data from the fixture.
=> Document how to restore from backup

requirements.prod.txt
Fixes #2107.
This is the latest 4.2 LTS release.
The changes since 4.2.4 are small in scope; mostly regression and security fixes.
=> Upgrade django to 4.2.16

assets/src/styles/base.css, templates/codelists/version.html
Fixes #2106 
The codelist versions are rendered in date creation order, but this is not always obvious to users.
Even then, we do not surface the creation of modification date anywhere.
For a user, trying to find a version of a codelist at a particular point in time, this change provides the neccesary information.
=> Add updated date to codelist version template

templates/codelists/_about_tab.html, templates/codelists/version.html
The current heading structure does not correctly reflect the content on the page, and misses multiple headings.
This PR makes sure that top-level headings are used on the page, and on the "About" tab.
=> Fix heading structure on the Codelist page

package-lock.json, package.json, vite.config.mjs
Add `vite-plugin-live-reload` to simplify reloading when changing styles.
This only takes effect when `npm run dev` is being used.
=> Set up Vite to reload pages on code changes

CHECKS, app.json
Mostly, we port the web health check from `CHECKS` to `app.json`. We set the `Host` header to prevent Django from raising a `DisallowedHost` error.
Why would Django raise this error? The web health check is performed by invoking `curl` from the Dokku host; an internal IP is passed as the URL,[^1] which means that Cloudflare DNS and nginx are bypassed. The `ALLOWED_HOSTS` setting limits the hosts that Django will serve,[^2] but we don't know the internal IP in advance, so we can't add it to the `ALLOWED_HOSTS` setting. Consequently, we set the `Host` header.
Closes #1868
---
I think we can test these changes with the following, removing the need for a second (dummy) deployment.
```
dokku checks:run opencodelists
```
[^1]: https://dokku.com/docs/deployment/zero-downtime-deploys/
[^2]: …
=> Move the web health check to `app.json`

opencodelists/management/commands/import_coding_system_data.py, opencodelists/tests/test_import_coding_system_data.py
Using `call_command` is better than `subprocess` because it’s simpler, faster, more readable, and doesn’t rely on `python` being available. In most cases, test cases should not use `subprocess` unless testing integration with external tools or the shell.  This change aligns the test with the rest of the module and codebase.
Also made some minor readability tweaks.
=> Remove use of `subprocess` in test

assets/src/styles/base.css, templates/registration/login.html, templates/registration/password_change_done.html, templates/registration/password_change_form.html, templates/registration/password_reset_complete.html, templates/registration/password_reset_confirm.html, templates/registration/password_reset_done.html, templates/registration/password_reset_form.html, templates/registration/register.html
During the workshop I noticed how these pages:
- Have no meta title
- Mostly have no on-page title
- Do not accurately describe the page
- Do not bold the labels in the forms
- Have full-width input boxes
- Do not make the asterisk red in the label
So I set about making some small simple fixes for these issues.
You can preview the pages on production using these links, and then change the URL for `http://localhost:7000` to view the local updated version.
- [Sign in](https://www.opencodelists.org/accounts/login/)
- [Sign up](https://www.opencodelists.org/accounts/register/)
- [Change password](https://www.opencodelists.org/accounts/password_change/)
- [Change password - done](https://www.opencodelists.org/accounts/password_change/done/)
- [Password reset - …
=> Improve the layout of the auth forms

app.json, opencodelists/tests/views/test_health_check.py, opencodelists/urls.py, opencodelists/views/__init__.py, opencodelists/views/health_check.py
When we deply OpenCodelists, Dokku starts each container and performs a health check to ensure the container has come up properly before routing traffic to it. These health checks are customisable (see [docs](https://dokku.com/docs/deployment/zero-downtime-deploys/)). Dokku only uses this health check when deploying new containers, it does not use it once the container has been deployed (we do have Freshping checking the site every few minutes though to make sure it's still working okay).
This change moves away from using the homepage as the health check endpoint and to a specific endpoint that will return 200 when the app starts and nothing else. Using the homepage as a health check is slower and makes a number of database connections, whereas this in theory decouples the app health …
=> Add custom endpoint for dokku healthchecks

mappings/__init__.py, mappings/bnfdmd/README, mappings/dmdvmpprevmap/README, opencodelists/management/commands/import_mapping_data.py, opencodelists/tests/test_import_mapping_data.py
Provide some feedback on how many rows are imported. This is useful as a cross-check against the number of mappings in the source file(s).
Also tidy up the simplicity, readability and documentation of this command.
First commit ("List available mappings in mappings.mappings.") has some accidental changes to `import_mapping_data.py` -- please ignore, this was WIP simplification of the `possible_modules` function I realized could go away altogether. Beware `git add -u`...
=> Report rows imported in import mapping command

DEPLOY.md
Updating the mapping in prod on dokku3 currently requires manually getting the file onto it and running the management command in the container. Let's at least note one way to go about doing the first bit, and where we put those files by convention.
=> Document uploading mapping files to dokku3

opencodelists/settings.py, opencodelists/urls.py, opencodelists/views/errors.py, templates/error.html
Closes #2168
- Adds custom error pages
- Link to the home page and to contact support
=> Add custom error page templates

justfile
This ensures that the pre-commit hook that runs `check` will prevent committing without running `fix` first to get the formatting right. Otherwise you can commit and push changes then run CI on a PR only to find it has formatting issues. This happened to me several times and it's annoying! Better to catch locally before committing. This is in line with what we do in job-server.
=> Include `format` in `check` command in `justfile`

requirements.prod.txt
This is a transitive dependency of environs, which we've already updated.
=> Bump python-dotenv from 1.0.0 to 1.0.1

coding_systems/versioning/tests/test_database_routing.py, opencodelists/tests/fixtures.py
Tidy up some stray references to make it clearer to what they refer. CodingSystemVersion was re-named to CodingSystemRelease in migration [`coding_systems/versioning/migrations/0002_rename_codingsystemversion_codingsystemrelease.py`](https://github.com/opensafely-core/opencodelists/blob/main/coding_systems/versioning/migrations/0002_rename_codingsystemversion_codingsystemrelease.py).
=> Tidy some stray references to CodingSystemVersion.

DEPLOY.md, DEVELOPERS.md, deploy/bin/backup.sh
Partially addresses #2151. ADR about the core backup strategy will be in a separate PR.
Taking backups via the sqlite CLI is simple and clean. We can restore from them.
We haven't been able to locally restore from the `dumpdata` fixtures-based backups. For now, keep the old-format backups just in case we want to try again to restore from them. After 30 days of creating new backups we can update the script to not consider the old format and location.
See [these comments](https://github.com/opensafely-core/opencodelists/issues/2151#issuecomment-2517804854) about the execution time and file system space requirements.
=> Take backups via `sqlite ".backup"`

assets/src/scripts/components/CodelistBuilder.jsx, assets/src/styles/base.css, templates/base.html, templates/builder/draft.html, templates/codelists/version.html, templates/codelists/version_diff.html
- **Create full_width_content block**
- This allows the normal content to fit to the Bootstrap standard container, whilst allowing wider content to extend to a maximum width of `1536px` (as per Tailwind CSS we use elsewhere)
- **Add break-word CSS utility**
- Allow URLs and long strings without spaces to break over lines in the sidebar (see diff page images below)
- **Improve diff view layout**
- Add a meta title
- Use the wide container
- Allow the left column to use more space at large screen widths
- **Update the codelist builder layout to full width**
- Add a meta title
- Use the wide container
- Allow the left column to use more space at large screen widths
- Allow right column to overflow in the X axis, rather than overflowing the page
- Add break-word utility class
- **Update …
=> Allow content to fill more of the viewport width

deploy/bin/backup.sh
Fixes #2214, which was broken. 
Within the container, /app/db.sqlite3 is an apparently empty DB, /storage/db.sqlite3 is the actual app DB of several GB. I'm not sure why the former exists. But this script was backing that up, not the intended DB.
For example, when this ran in production as scheduled the first time the produced backup file is only a few tens of bytes in size.
```
mikerkelly@dokku3:~$ ls /var/lib/dokku/data/storage/opencodelists/backup/db/ -lrth
total 4.0K
-rw-r--r-- 1 opencodelists opencodelists 114 Dec 12 01:00 2024-12-12-db.sqlite3.gz
```
=> Fix location of DB to take backup from

coding_systems/dmd/tests/test_import_latest_dmd_data.py, deploy/bin/import_latest_bnfdmd_cronfile, mappings/bnfdmd/data_downloader.py, mappings/bnfdmd/import_data.py, mappings/bnfdmd/tests/conftest.py, mappings/bnfdmd/tests/test_import_latest_data.py, opencodelists/management/commands/import_latest_data.py, requirements.prod.in, requirements.prod.txt
This PR largely makes use of pre-existing mechanisms to automatically download and load the BNF to dm+d mappings from the NHSBSA website.
The structure of the downloader largely mirrors that of those for the dm+d and SNOMED CT downloaders, as does the means of calling it and the scheduling of this call.
The web scraping code is mostly taken from OpenPrescribing with a couple of additions to parse the "valid from" date and to conform to the above described downloader pattern.
Some of this functionality (parsing of extra metadata and the ability to download multiple/specific releases of the mapping other than the latest) is not yet used, and so arguably could be removed until such time as we start showing the mapping metadata to users in the frontend and/or storing multiple versions of the …
=> Automate downloading of bnf dmd mappings

DEVELOPERS.md, deploy/bin/backup.sh, docker/dependencies.txt
Partially fixes #2151.
Zstandard is a fast, modern, lossless data compression algorithm. For these backup files, it gives marginally better compression ratios than `gzip` and much faster compression and particularly decompression. We want the backup process to be quick as it's a CPU-intensive activity that could affect site performance.
Experimental comparison of different compression utilities with their default settings:
```
Compression Test Results for 'latest-db.sqlite3':
Method | Compression Time | Original Size  | Compressed Size  | Compression Ratio
-------|------------------|----------------|------------------|------------------
gzip   | Time: 272.43 s   | Original: 4.1G | Compressed: 1.1G | Ratio: 73%
XZ     | Time: 3151.21s   | Original: 4.1G | Compressed: 606M | Ratio: 86%
7Z …
```
=> Make DB backup use Zstandard compression

.github/dependabot.yml, .github/workflows/update-python-dependencies.yml, justfile, requirements.prod.in
Fixes #2165.
This also pins Django to 4.2 LTS, for now, until we resolve issues in upgrading and test a later release.
=> Switch from Dependabot to update-dependencies-action

mappings/bnfdmd/data_downloader.py, mappings/bnfdmd/tests/conftest.py, mappings/bnfdmd/tests/test_data_downloader.py
download_latest_release() is the entry point for
the Downloader class that is called by the
import_latest_data management command.
This adds unit tests of that entry point given
that the latest mapping file has and has not
already been downloaded.
In case of the latter, the aforementioned
management command expects a ValueError to be
raised, this adds a test for that condition and a
fix such that the test passes.
[Sentry link for originating issue](https://ebm-datalab.sentry.io/issues/6157385078/?alert_rule_id=1877862&alert_type=issue&notification_uuid=cc036dbc-02c1-4ad9-bac6-8d0272d6e44c&project=5248013&referrer=slack)
=> Unit test and fix bnfdmd downloader

README.md, docs/adr/0001-backup-strategy.md, docs/adr/README
Partially fixes #2151.
This documents the current context and decisions after changes from #2151. I'm proposing that we keep this in draft until backup-related issues in the Onboarding OpenCodelists initiative are resolved or deferred. Then the outcomes can be combined, which will be easier to follow in future than multiple updates in a short period of time. E.g., #2225, #2128, #2153.
=> Document backup strategy in a draft ADR

opencodelists/settings.py
=> Increase db timeout to 90s

package-lock.json, package.json
Modal elements from the `react-bootstrap` package are not working with React v19. When clicking on an element that triggers a popup, the builder app will crash.
As we are using a legacy version of Bootstrap, we are pinned to a legacy version of `react-bootstrap` meaning the easiest path to fixing this is to revert React back to v18.
https://github.com/user-attachments/assets/261273a6-c71f-4767-8ef0-40b3f498b5f3
React was updated as part of a dependabot update here: https://github.com/opensafely-core/opencodelists/pull/2208
=> Revert React version to 18.3.1

.github/workflows/deploy.yml, .github/workflows/main.yml
Fixes #2260.
This prevents the case where two CI workflow runs can be triggered in quick succession, and the first triggered run may actually, on occasion, end up as the second deployment.
See opensafely-core/job-server@dc1bc43778f9ab74729abf6a3b9019cfc7162f45
There is more refactoring of the workflows that could be done here, but leaving this as a single, simpler change.
=> Separate deploy workflow from main CI tests

assets/src/styles/base.css, templates/codelists/version.html
For certain types of codelist (dm+d, SNOMED CT etc)
every time the coding system is updated the
versions of every codelist using this system
get updated and thus the updated_at field
is not very useful to understand the timeline
of codelist versions.
Therefore, switch to created_at which is
hopefully less confusing.
Part fix for #2285
=> Replace updated_at date with created_at date in CodelistVersion view

assets/src/scripts/components/CodelistBuilder.jsx, assets/src/scripts/components/ManagementForm.jsx
Linked to #2249 as part of a tidying up process before conversion to TypeScript.
This PR moves the management form out of the main CodelistBuilder class, and creates it as it's own functional component. This allows the form to use React hooks for state management, and moves the calculation of the codelist completion inside the component.
This simplifies the logic for showing the discard modal, and removes the need for the top-level `renderConfirmDiscardModal` component.
=> Create a management form component

deploy/bin/cronfile, deploy/bin/import_latest_release.sh, deploy/bin/sentry_cron_functions.sh
Reverting and re-applying bits of PRs is _fun_ , I missed an important change in rebasing for #2303 .
I've manually patched the cron file in prod as I was in there doing a manual job run anyway but this brings the codebase in line with it.
Additionally, I've fixed a couple of bugs that didn't show up when running locally:
* the path to the sentry functions script needs to be either absolute or derived from the calling script path, I've chosen the latter.
* "test" is a valid sentry monitor name, "import_data.sh_bnf.dmd" is not on account of the dots.
=> Fixup #2303

deploy/bin/backup.sh
Addition of Sentry cron monitoring has caused backups to fail.
Revert until this can be adequately debugged.
=> Reset backup.sh to 7984176

package-lock.json, package.json
Vite v6.0.9 is causing issues when running as a local dev server for assets, claiming a CORS misconfiguration. Vite v6.0.11 fixes this.
=> Update Vite dependency

assets/src/scripts/base.js, templates/base.html
Linked to opensafely-core/sysadmin#175
Hostname controls can be performed in the Plausible dashboard, and the events can be directly added to the script tag.
=> Move Plausible JS to HTML head element

DEPLOY.md, conftest.py, deploy/gunicorn/conf.py, opencodelists/tests/test_tracing.py, services/tracing.py
Fixes #2255 
Add username of opencodelist users to OTel spans.
**Why was this work done?**
We use [OpenTelemetry](https://opentelemetry.io/docs/what-is-opentelemetry/) to instrument opencodelists such that when users make requests, we can capture data about these requests in [traces and spans](https://opentelemetry.io/docs/concepts/signals/traces/#spans) emitted by our code. We send this data to [Honeycomb](https://docs.honeycomb.io/get-started/start-building/application/traces/) in order to view and interrogate it, helping us to understand the internal state of our system. Previously, the traces and spans emitted from opencodelists did not include information to identify, or query by, logged-in users. Adding the username of opencodelist users as a span attribute allows us to do this, and …
=> Enhance otel spans with an identifier for logged in users

deploy/bin/backup.sh, deploy/bin/sentry_cron_functions.sh, docker/dependencies.txt, opencodelists/tests/test_sentry_cron_functions.py
Brings back functionality reverted in https://github.com/opensafely-core/opencodelists/commit/555bc71debb0bd40944811f82d0569886d7e5027 but with three crucial bugfixes:
* correct derivation of script name for sentry
monitor name
* missing dependency for `curl`
* Fix trailing spaces in cron parsing
Whilst allowing backup script to continue if sentry logging fails for some reason
=> Reintroduce sentry monitoring of backups

codelists/tests/test_codeset.py, coding_systems/snomedct/tests/test_ecl_parser.py, requirements.dev.in, requirements.dev.txt
=> Replace use of pytest-subtests with `parametrize`

deploy/bin/backup.sh
These lines were gradually removing old-format backups as they aged out past 30 days. Now there are none left, they do no useful work and are no longer required.
We changed the format of backups from `.json` to `.sqlite3` in #2214 (cdbacb67c62fe6501c6c5164eda62937c71373a1)  on Dec 9, 2024.
We changed the compression format from `gzip` to `Zstandard` in #2248 (79841764b49733510c191bbb2aea3bf5860550a5) on Dec 16, 2024.
=> Remove old backup format cleanup actions

codelists/migrations/0016_auto_20201116_1754.py, codelists/migrations/0030_auto_20210412_0947.py, codelists/migrations/0033_auto_20210429_1029.py, codelists/models.py, coding_systems/base/tests/dynamic_db_classes.py, coding_systems/base/tests/test_import_data_utils.py, coding_systems/bnf/tests/test_import_data.py, coding_systems/ctv3/tests/test_import_data.py, coding_systems/dmd/tests/test_import_data.py, coding_systems/icd10/tests/test_import_data.py, coding_systems/snomedct/tests/test_import_data.py, coding_systems/versioning/tests/test_database_routing.py, coding_systems/versioning/tests/test_models.py, opencodelists/settings.py, pyproject.toml, requirements.dev.txt, requirements.prod.in, requirements.prod.txt, templates/base.html
Fixes #2115.
This requires a workaround of the coding systems tests that use databases dynamically, due to changes in Django 5.1. We agreed in #2115 that working around the new restrictions was the best thing to do, to allow the upgrade without delay. In future, we may have to revisit this code and associated tests, either for future Django changes or to make maintenance and improvements easier. 
TODO:
=> Update to Django 5.1

app.json
At 1am the current backup risks running concurrently with the dm+d imports on Wednesdays that run
from 11pm to ~3am.
=> Run backups at 5am

opencodelists/settings.py, opencodelists/tests/integration/test_db_settings.py
Fixes #2268.
We think immediate mode in particular might help resolve 'database is locked' errors.
Options used here are largely following suggestions from the article https://kerkour.com/sqlite-for-servers as referenced in #2268/#2251, some of which I found Django applies by default. See commit messages for more discussion. In particular, I think we should not be using an excessively large timeout as this can cause users to wait a long time if there was a problem with the site. Let's try 5 seconds and see if the other settings changes resolve the issue, then gradually increase the value if there are still many errors.
I discovered that unfortunately we have been configuring the timeout settings for the default database incorrectly, so #1143, #1811, #2276 increasing it from5 ro 30, 60, …
=> Improve sqlite configuration options

opencodelists/forms.py, opencodelists/tests/test_forms.py
Fixes #1474.
Otherwise there can be an unhandled exception and 500 error if trying to upload a file encoded differently, or if an XLSX is accidentally uploaded in place of CSV text.
I considered looking at the file extension to try to provide extra hints but it didn't seem worth the complication, the error message tells them what they need to do clearly enough.
There were no tests of this form specifically so I added a basic valid form test as well as the test of the error case.
[codelists/tests/views/test_codelist_create.py](https://github.com/opensafely-core/opencodelists/blob/main/codelists/tests/views/test_codelist_create.py) has tests of the view as a whole but they seemed to relate to behaviour before or after the form is processed.
=> Codelist create form: Check for `UnicodeDecodeError`

templates/base.html
The "2022" potentially makes the site look unmaintained, which isn't the case.
=> Use the current year in copyright notice

deploy/bin/sentry_cron_functions.sh
=> Correct datatypes for sentry monitor config

opencodelists/settings.py
This is no longer needed. It was added in
https://github.com/opensafely-core/opencodelists/pull/1397 for management command `coding_systems/versioning/management/commands/migrate_coding_system.py` which no longer exists. There are no references to the setting in the repo.
=> Remove `DATABASE_DUMP_DIR` setting

.github/ISSUE_TEMPLATE/default.md
This is intended to make it easier for us to create issues that are inline with the delivery tasks guidance and to help ensure we have the information we need when picking up the issue.
=> Create a default issue template

justfile
I regularly find myself wanting to run a Django management command with the devenv's environment with something like .venv/bin/python3.12 manage.py command. Let's add a recipe to make that slightly easier.
`migrations` command provides one command to update the DB after models changes.
=> Add manage and migrations convenience justfile recipies

deploy/bin/backup.sh
using -name to exclude files from `find` when the pattern contains directory separators (which in the case of $BACKUP_FILEPATH it does) gives the following error:
"find: warning: ‘-name’ matches against basenames only, but the given pattern contains a directory separator (‘/’), thus the expression will evaluate to false all the time. Did you mean ‘-wholename’?"
and fails to exclude the most recent backup file as desired.
Using -wholename as suggested fixes this.
=> Fix removal of old sanitised backups

deploy/bin/backup.sh
Use relative path for target as per regular backup symlink
testing:
```sh
I have no name!@0cf1ecf54587:/app$ cd deploy/bin/
I have no name!@0cf1ecf54587:/app/deploy/bin$ BACKUP_DIR="$DATABASE_DIR/backup/db"
BACKUP_FILENAME="$(date +%F)-db.sqlite3"
BACKUP_FILEPATH="$BACKUP_DIR/$BACKUP_FILENAME"
SANITISED_BACKUP_FILENAME="sanitised-$BACKUP_FILENAME"
SANITISED_BACKUP_FILEPATH="$BACKUP_DIR/$SANITISED_BACKUP_FILENAME"
I have no name!@0cf1ecf54587:/app/deploy/bin$ echo "$SANITISED_BACKUP_FILENAME"
sanitised-2025-03-25-db.sqlite3
I have no name!@0cf1ecf54587:/app/deploy/bin$ echo "$SANITISED_BACKUP_FILEPATH"
/storage/backup/db/sanitised-2025-03-25-db.sqlite3
I have no name!@0cf1ecf54587:/app/deploy/bin$ ln -sf "$SANITISED_BACKUP_FILENAME.zst" "$BACKUP_DIR/sanitised-latest-db.sqlite3.zst"
I have …
```
=> Fix sanitised backup symlink

docker/Dockerfile
Tailwind requires the templates to be able to build the stylesheet.
[Prior art from Job Server](https://github.com/opensafely-core/job-server/blob/741168fa369be20c5d3b1615710c3c1d5804a027/docker/Dockerfile#L46-L49).
=> Fix for missing templates in Docker npm build

DEVELOPERS.md
These were a little out-of-date and missing some details. Fixes #2375
- Add a section for each directory in the repo structure.
- Replace "project root" with a slightly fuller explanation.
- Remove mention of nonexistent "project" model in `opencodelists` app.
- Explain the `mappings` structure a little bit more.
=> Update repo structure docs

.github/workflows/deploy.yml
Fixes #2391.
Mirrors what we did in:
opensafely-core/job-server#5053
=> Finalize Sentry release after deployment completes

.vscode/launch.json
Added some debugging shortcuts for vscode users. One click setup for:
1. Launching opencodelists in debug mode
2. Debugging the current test file
3. Debugging the current PlayWright test file (in anticipation of PlayWright tests)
=> Added debug config for vscode

deploy/bin/sanitise_backup.py
use `fake_username` rather than `username` for the local email part of the sanitised email
=> Fix emails in sanitise_backup.py

assets/src/scripts/components/CodelistBuilder.tsx, assets/src/scripts/components/MoreInfoModal.tsx
When testing the builder as part of unrelated work, I noticed a significant lag between clicking to update the status of a tree item and seeing that change reflected in the UI.
The issue was caused by a performance bottleneck: when a status is updated, all hidden modals in the tree rows *below* that item were having their text recalculated. This becomes particularly expensive in large or deeply nested trees.
The solution is to defer text calculation until a modal is actually opened. Since this text can be computed just before the modal is added to the DOM, we avoid unnecessary recalculations and improve performance significantly.
While investigating this issue, I also made two additional improvements:
1. **Removed the `_isMounted` variable** and its related code from `CodelistBuilder`. …
=> Fix slowdown due to modal text recalculation

opencodelists/settings.py, opencodelists/tests/integration/test_db_settings.py
We changed some settings to help reduce the number of "Database is locked" errors, which seems to have helped, but there are still some. Let's try increasing the timeout to 15 seconds from the default 5 in case this helps with some of the remaining cases. See comments in file and https://github.com/opensafely-core/opencodelists/issues/2251 for discussion.
Fixes #2251, potentially.,
=> Increase DB transaction timeout from 5 to 15s.

DEVELOPERS.md
Added in https://github.com/ebmdatalab/team-manual/pull/1060, let's add breadcrumbs from DEVELOPERS.md to the playbook.
=> Link to playbook for using sanitised prod data for local development

coding_systems/versioning/models.py, justfile, opencodelists/management/commands/setup_local_dev_databases.py, opencodelists/tests/management/commands/test_setup_local_dev_databases.py
Closes #2313.
A `setup_local_dev_databases` management command deletes, rebuilds and populates databases (dbs). This is called from a `just` recipe which deletes and rebuilds the core db. Both are safe by default. The result is a lightweight local development setup that uses our test data. 
You can use the `just` recipe in **safe-mode**: `just build-dbs-for-local-development`
To actually **delete local dbs** if you have them, pass the `nuclear` argument: `just build-dbs-for-local-development nuclear`
Originally, deletion of the core db occurred inside the management command. However, this led to unexpected behaviour. When a Django management command is invoked, it triggers `django.setup()` and the [app initialization process](https://docs.djangoproject.com/en/5.1/ref/applications/#initiali …
=> Populate development dbs with test fixture data

assets/src/scripts/components/CodelistBuilder.tsx, assets/src/scripts/components/EmptyState.tsx
Part of [Improve instructions to users on initial codelist creation page #2395](https://github.com/opensafely-core/opencodelists/issues/2395).
=> Add instructions to initial codelist builder template

DEVELOPERS.md
Note that the playbook now also describes downloading the coding systems databases, as well as getting a sanitised copy of the core database. See https://github.com/ebmdatalab/team-manual/pull/1064 / [the team manual](https://bennett.wiki/tech-group/playbooks/opencodelists/#downloading-coding-systems-databases).
Those details are there rather than in DEVELOPERS.md as they include details about the internals of our specific infrastructure which is somewhat sensitive/security-related.
=> Add pointer to playbook for coding system download.

assets/src/scripts/components/CodelistBuilder.tsx, assets/src/scripts/components/SearchForm.tsx, builder/tests/test_views.py, builder/views.py, codelists/models.py
Fixes #2451
New search box now looks like:
All help text (about searching with `code:` prefixes is now gone), except for the bit that tells you that you can do wildcard searching for ICD-10 codes:
=> Adds a search box toggle - search by term OR seach by code

codelists/tests/test_forms.py, coding_systems/bnf/tests/test_import_data.py, coding_systems/ctv3/tests/test_import_data.py, coding_systems/icd10/tests/test_import_data.py, coding_systems/snomedct/tests/test_coding_system.py, coding_systems/snomedct/tests/test_import_data.py, conftest.py
Relates to #2403. Most tests cases in the repo can't be run independently because there are undeclared dependencies between their fixtures, that are only resolved by running groups of tests with mutually-compatible sets of fixtures together. If we make those dependencies explicit, we can run tests in isolation.
Several fixes combined in one PR as tests may be affected by more than one of these issues, preventing them from being run in isolation until all changes are in place. See commit messages for more details. See #2403 for more on the investigation.
The work done by the `testing_db_setup` fixture could also possibly have been applied by overriding [`django_db_setup`](https://pytest-django.readthedocs.io/en/latest/database.html#django-db-setup), or only when individual fixtures need it …
=> Make tests runnable in isolation

assets/src/scripts/__tests__/components/Metadata.spec.tsx, assets/src/scripts/components/CodelistBuilder.tsx, assets/src/scripts/components/Metadata.tsx, assets/src/scripts/components/Title.tsx
Closes [#2446](https://github.com/opensafely-core/opencodelists/issues/2446)
Metadata is currently shown in the sidebar, but we are moving to the sidebar being for searching and interacting with the codelist. For this reason, we have moved the metadata under the title.
It also means we can create a `<Metadata />` component, and add tests with 100% coverage for the component.
=> Move metadata under title in builder

assets/src/scripts/components/CodelistBuilder.tsx, assets/src/scripts/components/Search.tsx, assets/src/scripts/components/SearchForm.tsx
As per this ticket (#2450) this changes the previous searches component into a Card element. It now looks like this:
and like this when a search is selected:
=> Make the "previous searches" component into a Card

codelists/actions.py, codelists/tests/test_actions.py, opencodelists/tests/fixtures.py, opencodelists/tests/views/test_user_create_codelist.py
- this allows users to review and potentially add to uploaded codelists before moving to review/published
- codelists created via `create_or_update_codelist()` still default to `PUBLISHED` status. This method is only used by the API, where for bulk uploads you probably still want to go straight to published rather than draft
- the logic for uploading unsupported csvs (e.g. dmd and opcs4) via /codelist/user/{user}/add/, is unchanged. CSVs uploaded in this way cannot be edited because we don't allow searches in those dictionaries. The existing behaviour is to put the codelist in the `UNDER_REVIEW` status, which allows checking before publishing - this seems exactly what we want in this situation
Resolves https://github.com/opensafely-core/opencodelists/issues/1836.
=> Uploaded CSV codelists now default to DRAFT status

opencodelists/tests/fixtures.py
These were found with [`pytest-deadfixtures`](https://github.com/jllorencetti/pytest-deadfixtures) which isn't very actively maintained and had quite a few false positives (mainly around fixtures used via decorators such as `autouse=True` or `usefixtures`).
I also tried [`pytest-unused-fixtures`](https://github.com/mikicz/pytest-unused-fixtures/) though this didn't catch anything.
So it's probably not worth adding these to our tests or CI checks, but it was useful for a one-time run.
=> Remove unused test fixtures

coding_systems/base/tests/dynamic_db_classes.py, coding_systems/base/tests/test_import_data_utils.py, coding_systems/bnf/tests/test_import_data.py, coding_systems/ctv3/tests/test_import_data.py, coding_systems/dmd/tests/test_import_data.py, coding_systems/icd10/tests/test_import_data.py, coding_systems/snomedct/tests/test_import_data.py, coding_systems/versioning/tests/test_database_routing.py, coding_systems/versioning/tests/test_models.py
Fixes #2493 and fixes #2301. See #2403.
This facilitates running two tests that were not made independently-runnable in #2492.
A slightly earlier version of this PR was tested with all tests running independently, except for the database timeout which was changed in case there were issues with it. (Which was mentioned in the comments for the helper script to run the tests independently.)
The changes made since then are essentially comment/commit message changes and rebasing.
=> Make remaining coding systems tests independent

codelists/tests/test_db_utils.py, coding_systems/bnf/tests/test_import_data.py, coding_systems/versioning/tests/test_models.py, conftest.py, opencodelists/tests/fixtures.py, opencodelists/tests/integration/test_db_settings.py, opencodelists/tests/templatetags/test_widget_with_classes_filter.py
While digging around the tests, there were a few style inconsistencies, and possible simplifications.
These were found using the [flake8-pytest-style rules in Ruff](https://docs.astral.sh/ruff/rules/#flake8-pytest-style-pt). With the relative complexity of tests and fixtures in this codebase, I think there's some benefit in having a more consistent style. 
However, there's still some debate about [which of the flake8-pytest-style rules](https://github.com/astral-sh/ruff/issues/8796) are worthwhile, so if we were to apply this as a setting, we might want to pick and choose certain rules only.
=> Tidy up tests slightly

opencodelists/tests/views/test_user.py, opencodelists/views/user.py, templates/opencodelists/_codelist_links.html, templates/opencodelists/that_user.html, templates/opencodelists/this_user.html
The list of codelists now displays the metadata of:
- terminology (SNOMED, ICD10 etc.)
- the number of codes
- the last updated time
It look like this:
Fixes #2489
=> Add metadata to the user list of codelists

assets/src/scripts/components/CodelistBuilder.tsx, assets/src/scripts/components/EmptySearch.tsx, builder/views.py
If you do a search that returns no results we now:
- display some helpful text so it's both clearer that nothing was found, but also what you might want to do next
- no longer display the banner at the top as it duplicates info elsewhere
Now looks like this:
Fixes #2522
=> Better help and layout on the "no results" page in the builder

.github/workflows/main.yml
This happens separately in `test-functional` too.
Removing this duplicate was part of #2421 at one point. However, the relevant commit must have got lost in the final rebasing somehow.
(I skimmed the merged form of #2421 and this looks to be the only anomaly there.)
=> Remove duplicate functional test CI step

assets/src/styles/base.css, templates/codelists/version.html
Closes #2526 
[ ] Restyled and moved the create new/update, publish and delete version buttons to the top right of the page
[ ] Updated sidebar styling
[ ] Moved the codelist metadata to sit under the title
[ ] Added coloured badges for codelist status to "Versions" component
_Under review codelist_
_Published codelist_
_Published codelist with an organisation_
=> Update codelists version page to match builder changes

assets/src/scripts/__tests__/components/Search.spec.tsx, assets/src/scripts/components/CodelistBuilder.tsx, assets/src/scripts/components/Search.tsx
Builder pages are currently publicly visible, so that researchers can share links of work in progress codelists. We expect this to continue. Therefore it's possible to view a codelist Builder with Searches that have a delete URL but where the user doesn't have permission -- this is exactly when `isEditable` is `false`. We should not display the button if the user does not have permission to delete the search.
Fixes #2528.
=> Remove "Remove" link from builder page `Search` if not editable.

docker/docker-compose.yaml, docker/justfile, justfile
Fixes #2479 
If the `DATABASE_DIR` env var is set, mount this path under the same path inside the dev docker container so the dev docker container behaviour mirrors that of the local environment.
Change any hard-coded "dev" environment strings in docker just recipes to use `env` variable instead so all recipes respect this new behaviour.
Ensure `docker-serve` recipe is unaffected if called with an environment other than "dev" (i.e. "prod").
=> Mount DATABASE_DIR in dev container if defined

coding_systems/dmd/fixtures/asthma-medication.dmd_test_20200101.json
The current dm+d test coding system fixture is extremely minimal and inadequate for the forthcoming tasks to make the `dmd` coding system a `BuilderCompatibleCodingSystem`.
In order to keep in the theme of "asthma medication", this PR adds subset of the salbutamol tree to the dmd fixture:
- Add "salbutamol" VTM and Ing,
- plus 10 descendant VMPS,
- plus 10 descentant AMPS,
- plus all supporting referenced entities.
This should give adequate data to test the search and hierarchy methods required to satisfy the
`BuilderCompatibleCodingSystem` interface and give reasonable numbers of entities to test template rendering for e2e playwright tests without becoming unreasonably large on disk or intractable.
JSON chunks were added by navigating the model tree from the "salbutamol" VTM and running …
=> Expand dm+d test fixture data

codelists/coding_systems.py, codelists/models.py, codelists/views/version.py, codelists/views/version_diff.py, coding_systems/base/coding_system_base.py, coding_systems/dmd/coding_system.py, coding_systems/dmd/fixtures/asthma-medication.dmd_test_20200101.json, coding_systems/dmd/tests/test_coding_system.py, opencodelists/forms.py, opencodelists/views/user_create_codelist.py
Define a hierarchy of entites from a subset of the dm+d coding_system which will be presented to the builder via the `ancestor_relationships` and `descendant_relationships` methods.
All AMPs have an ancestor VMP, most but not all VMPs have an ancestor VTM so this must be handled in these methods.
AMPPs and VMPPs are excluded from this hierarchy as no user need for them has been determined, and codes for these types of entity are not present in the data sets made available through OpenSAFELY. Additionally, AMPPs have dual ancestors of AMPs and VMPPs which would be challenging to represent in these methods.
fixes #2506
=> Implement VTM-VMP-AMP hierarchy

DEVELOPERS.md, codelists/coding_systems.py, coding_systems/base/coding_system_base.py, coding_systems/versioning/tests/test_views.py, opencodelists/forms.py, opencodelists/tests/fixtures.py, opencodelists/tests/test_forms.py, opencodelists/tests/views/test_user_create_codelist.py, opencodelists/views/user_create_codelist.py, templates/opencodelists/user_create_codelist.html
Enables any builder-compatible coding system to be marked as experimental (via the `is_experimental` boolean). By default experimental coding systems are not displayed on the create new codelist screen, unless you visit the page with the following query param: `/users/<username>/new-codelist/?include_experimental_coding_systems`
Experimental coding systems are clearly marked as such to ensure that in the unlikely event someone visits the page unintentionally, that they won't inadvertently use an experimental coding system without understanding the risks.
The page looks like this (with CTV3 change temporarily to be experimental):
And the drop down:
Fixes #2503.
=> Allow experimental coding systems to be hidden behind a flag

coding_systems/dmd/coding_system.py, coding_systems/dmd/fixtures/asthma-medication.dmd_test_20200101.json, coding_systems/dmd/tests/test_coding_system.py
- Search by code returns the code if it is an AMP, VMP or VTM. If the code is an ingredient it returns all VMPs containing that ingredient, and all VTMs related to those VMPs
- Search by term finds all AMPs, VMPs and VTMs whose Name, Previous name, Abbreviated name, or description contains the search term. (not all models have all the searched properties)
- To improve the searches we add part of the co-codamol hierarchy. This is so that a search for the ingredient "codeine" correctly returns VTMs and VMPs whose names are just co-codamol i.e. no mention of codeine.
- I've also added fake strings (like TEST_STRING_for_AMP_abbreviation) so we can test that it is correctly searching all fields.
Fixes #2505
=> Implement `search_by_ code` and `search_by_term` for DMD

templates/codelists/version.html
Closes #2563
The team [decided](https://github.com/opensafely-core/opencodelists/issues/2563#issuecomment-2893927190) that we wanted to keep the current behaviour of our codelist title badges.
This work adds a comment to the code documenting the above decision to help future travellers who may wonder why there isn't a title badge for "Published".
=> Add comment about published codelist title badges

assets/src/scripts/components/CodelistBuilder.tsx, assets/src/scripts/components/DescendantToggle.tsx, assets/src/scripts/components/MoreInfoModal.tsx, assets/src/scripts/components/TreeRow.tsx, assets/src/scripts/components/TreeTable.tsx, assets/src/styles/_builder.css, assets/src/styles/base.css
Closes https://github.com/opensafely-core/opencodelists/issues/2555
Changes made as part of this PR:
- Overflow scrolling is moved to a per section basis, so the whole page no longer scrolls horizontally for one particularly long code name
- The more info modal button now displays the text "More info"
- This button only shows on hover of a row
- The row that is being hovered has a background to highlight it
- To simplify the visual design, the brackets have been removed from around the code, and the colouring has been updated to more clearly identify the codes which have been excluded, or are in conflict
https://github.com/user-attachments/assets/d65c2471-c740-4631-9357-3ffb457dea42
=> Update the styling and content of the tree row modal

assets/src/scripts/_hierarchy.ts
Part of #2532 - but does not close the issue ([see comment](https://github.com/opensafely-core/opencodelists/issues/2532#issuecomment-2949199590)).
This simply fixes the issue of the React builder app crashing, so that users can potentially get themselves out of the broken state. it does not fix the underlying code issues.
=> Fix for builder in broken state

builder/views.py
Fixes #2534.
The previous behaviour was such that:
1. Enter a search.
1. That search appears in the list of searches.
1. Select a code.
1. Delete the search.
1. See no searches listed at all.
1. Search again.
1. See your search and "no search term" then appear as a search.
This commit changes the behaviour so that "no search term" appears even
with no other valid searches. This makes the UI more consistent by not
making "no search term" appear when you actually enter another search.
=> Show "no search term" when last search deleted

requirements.dev.in, requirements.dev.txt, requirements.prod.in, requirements.prod.txt
Dependabot want to use requests>=2.32.4 to fix a security vulnerability for both dev and prod, but can't bump it past 2.32.3. I'm not sure why because all the dependencies (django-anymail, and opentelemetry-exporter for prod at least) are pinned to compatible ranges (~=2.7 and >=2.4.3). Manually forcing it to use >=2.32.4 to get round this.
=> Pin minimum version of `requests` package to 2.32.4

builder/tests/test_views.py, builder/urls.py
This ensures that the view cannot receive non-int `search_ids`, which would cause a `ValueError` when passed to `get_object_or_404` as the `id` parameter.
Partially resolves #2609.
=> Use path converters to ensure `int` used in `search` and `search-delete` URL patterns

builder/actions.py, builder/tests/test_actions.py
Fixes #2532 
The issue was that when deleting a search, any codes not part of any other search and not included (or descendants of included codes), were deleted. But if those codes were a descendant of an unselected orphaned code (one found by a search, included, then the search was deleted, then the code was set back to unresolved), then they would still appear as descendants of the unselected orphaned code, but their definitions weren't provided from the backend because the codes had been deleted from the codelist. 
The quick fix would have been to not delete children of unselected orphaned codes when a search was deleted. However the underlying issue is that while it makes sense to keep an "included" code even if you delete its search term, it doesn't make sense to still keep that code …
=> Fix broken state issue with orphaned codes

codelists/urls.py
`CodeliveVersion` hashes are hex-strings but tags are free text, so `tag_or_hash` uses the less-restrictive `str:` path converter.
This makes it clear what kind of values may match in the pattern.  There is some value in using a path converter here for consistency with other `urls.py`, as a form of documentation, future-proofing, and to avoid URL pattern collisions.
I'm not including tests as the `str:` path converter is in-built Django functionality and so broad that it's not clear what the test would actually do.
Partially resolves #2609.
=> Use `str` path converter for `tag_or_hash` in URL patterns

codelists/tests/views/test_version.py, templates/codelists/_medication_warning_banner.html, templates/codelists/version.html
Fixes #2394 
Looks like:
- only displays for codelists that are
- published, and
- either dmd or bnf
- appears on ALL codelists. I considered just on old ones, but I think the way the message is worded it's sufficiently generic. Also, if it's the first med codelist you've created, it's still useful to know that you can't necessarily rely on it if you only get round to using it in a few months.
-  message is tailored so that
- if you're logged in, the "or create a codelist" is hyperlinked to the create page
- if it's a codelist that you can create a new version of, then it tells you that instead of saying you can create a new codelist
=> Add a warning banner to medication codelists

assets/src/scripts/codelists-list.js, assets/src/styles/_codelists_list.css, assets/src/styles/base.css, opencodelists/tests/functional/conftest.py, opencodelists/tests/functional/test_build_codelist.py, opencodelists/tests/views/test_user.py, opencodelists/views/user.py, templates/opencodelists/_codelist_links.html, templates/opencodelists/that_user.html, templates/opencodelists/this_user.html, vite.config.mjs
Fixes #2538 
The My Codelists page is now a searchable table as shown here:
[Screencast from 25-06-25 11:34:04.webm](https://github.com/user-attachments/assets/b11dcb1b-3527-42c3-b191-e9fe989bbd08)
When viewing another user's (published) codelists it looks like:
=> Improve the styling of the My Codelists page

codelists/api.py, codelists/api_urls.py, codelists/tests/test_api.py
Fixes #2676.
This is no longer needed following the end-of-life of cohort-extractor.
=> Remove `dmd_previous_codes_mapping`

codelists/views/version.py
As written, this was ineffective.
`format_html()` takes a string to be formatted, and then escapes the other arguments and keyword arguments passed to it. Passing only a single, already formatted string results in no escaping.
Our incorrect use was deprecated in Django 5.0. It will result in a `ValueError` in Django 6.0:
https://adamj.eu/tech/2023/06/15/format-html/
=> Correct use of `format_html()`

coding_systems/dmd/coding_system.py, coding_systems/dmd/tests/test_coding_system.py
Fixes #2696 
Rather than developing a new display mechanism for "description", this uses the existing "synonym" mechanism for AMP descriptions as this field is more akin to a synonym than an actual description.
=> Add AMP descriptions as synonyms

templates/codelists/_about_tab.html
A flexbox margin top issue is causing the About tab lower data to be pushed over the footer. This PR removes the margin top, which fixes the issue.
[Example link](https://www.opencodelists.org/codelist/opensafely/ace-inhibitor-medications/2020-05-19/)
=> Fix for tab data being pushed over footer

codelists/actions.py, codelists/api.py, codelists/scripts/bulk_import_codelists.py, codelists/scripts/nhsd_primary_care_refsets.json, codelists/scripts/update_pcd_refsets.py, codelists/tests/test_actions.py, coding_systems/versioning/views.py
Fixes #2668 
Running the script provides an interactive CLI to update the NHS PCD refsets. Previously this was [a manual process](https://github.com/opensafely-core/opencodelists/issues/2163).
This addresses the automation part of #2671 but not the scheduling part.
The commit messages provide more detail as to the exact behaviour of the script. But the key things are:
- we now overwrite the name and description of the codelists as we want them to always match the latest (and sometimes the names change)
- the description now includes the OGLv3 message to comply (we think) with the licence
- any unfound codes (e.g. medication codes in a clinical refset) are automatically omitted and explicitly listed in the description
The first time this runs we will need to take some extra steps. These …
=> Add a script to update the NHS PCD refsets automatically

assets/src/scripts/__tests__/fixtures/version_from_scratch.json, assets/src/scripts/__tests__/fixtures/version_with_complete_searches.json, assets/src/scripts/__tests__/fixtures/version_with_no_searches.json, assets/src/scripts/__tests__/fixtures/version_with_some_searches.json, builder/management/commands/generate_builder_fixture.py, builder/views.py, templates/builder/draft.html
As they are no longer used in the builder.
This PR also fixes the broken test fixture generation, and updates the fixtures.
=> Remove unused included_codes and excluded_codes

assets/src/scripts/feedback-form.js, assets/src/styles/feedback-form.css, templates/_feedback_form.html, templates/base.html, templates/builder/draft.html, templates/codelists/index.html, templates/codelists/version.html, vite.config.mjs
Closes #2621.
This work created a floating feedback button element to surface our new OpenCodelists feedback form to our users. The form is shown on the following pages, [per TeamREX discussions](https://bennettoxford.slack.com/archives/C069SADHP1Q/p1751444354952509?thread_ts=1751382383.555059&cid=C069SADHP1Q):
- The builder page (`templates/builder/draft.html`)
- The published and under-review codelist version page (`templates/codelists/version.html`)
- The post-search page (`templates/codelists/index.html`)
=> Created feedbackForm component and assets

coding_systems/versioning/apps.py, opencodelists/wsgi.py
- When the db is accessed in the AppConfig.ready() method, django complains that you shouldn't
- By moving it to the wsgi file it means it gets run on first load of the application
- Migrations will have already run by this point, as they are in the dokku release phase, which completes before the wsgi app is launched as part of the dokku web phase.
- We defer the import of the method into a `run_startup_tasks` method (rather than at the top of the wsgi file) to avoid an existing circular dependency
fixes #2289
=> Prevent start up warning by moving coding system update to wsgi

assets/src/scripts/components/Codelist/MoreInfoModal.tsx, templates/opencodelists/user_create_codelist.html
Partially address #2648
Specifically implements:
- Number of Clicks on ‘More info’- 
- Percentage of new codelists created using dm+d vs BNF
Plausible will start capturing these events once they're in production. The Plausible dashboard will then need to be updated to display these events.
=> Capture event data in Plausible for how users interact with OpenCodelists

assets/src/scripts/__tests__/builder/codelistbuilder.test.jsx, assets/src/scripts/__tests__/components/Metadata/MetadataForm.spec.tsx, assets/src/scripts/_utils.ts, assets/src/scripts/components/Layout/MetadataTab.tsx, assets/src/scripts/components/Metadata/MetadataForm.tsx, assets/src/scripts/types.ts, assets/src/styles/_builder.css, package-lock.json, package.json
The current implementation of the metadata tab requires that all data updates are handled in the CodelistBuilder (class) component. We should simplify this so that the individual components can handle their own state, and POST changes to the server. This PR is the first of a number of PRs to simplify the component architecture.
In this PR I have:
- Created a new MetadataForm component
- Used that component for the description field
- Styled it using Bootstrap card classes (as opposed to react-bootstrap, which contains many context providers)
- Used react-query to hold the state of the metadata, and update it upon the POST request to the server
- Added tests which use react-query for testing, and nock for mocking API requests
- Removed any tests for the existing description functionality
- …
=> Replace metdata description component in codelist builder

builder/actions.py, builder/tests/test_actions.py, builder/views.py
Fixes #2733 
If there are too many codes returned we hit a limit in sqlite and an unhandled exception is thrown. This limit is currently 250,000 codes in an `IN` clause. However, large numbers of codes returned by a search is probably a sign the user has made a mistake or has not been specific enough. They would then need to include/exclude all codes which would take too long. So instead we set a much smaller limit (20,000 codes) and tell the user if their query exceeded that.
I have taken a look at existing searches that exceed this limit and have summarised them here. These searches will still exist in the system, but I'm happy that we don't need to support any of them in future.
|Term|Number of codes returned|
|---|---|
|NA|141569|
|PE|123320|
|x|82434|
|a|67427|
|1|21605|
|Term|Number …
=> Limit number of codes returned by search

assets/src/scripts/__tests__/builder/codelistbuilder.test.jsx, assets/src/scripts/components/CodelistBuilder.tsx
Currently we keep tab navigation in the browser history, but only for under review and published codelists. This adds it to the draft codelists as well so that you can:
- navigate back and forward through the codelist and metadata tabs
- navigate directly to the metadata tab by appending #metadata to the url
- refresh the page when viewing the metadata and not navigate back to the codelist tab
=> Preserve history on navigating between the codelist and metadata tabs

assets/src/scripts/components/Cards/Searches.tsx, assets/src/scripts/components/Cards/Summary.tsx, assets/src/scripts/components/Cards/Tools.tsx, assets/src/scripts/components/Cards/Versions.tsx, assets/src/scripts/components/Codelist/Row.tsx, assets/src/scripts/components/Codelist/StatusToggle.tsx, assets/src/scripts/components/CodelistBuilder.tsx, assets/src/scripts/components/Layout/Header.tsx, assets/src/scripts/components/Layout/Sidebar.tsx
Where the only thing being applied is styling. This reduces the amount of components and context providers in the React component tree.
Images below from the React Dev Tools
=> Replace React Bootstrap with HTML classes

codelists/presenters.py, codelists/views/version_download_definition.py
We hide the "Download definition" for codelists without a codeset, but it's still possible to manually create the URL. This then triggers an unhandled exception. This code handles it and returns a 400 to the user with an explanation.
Fixes #2785
=> Handles missing codeset in definition download

codelists/tests/views/test_version.py, templates/codelists/version.html
Fixes #2784 
- If the CSV is downloadable, we show the "Download CSV" button
- If not downloadable, but the viewer can edit the codelist, then we display the button, but disabled, with a useful tooltip about what they can do about it
- If not downloadable, and the viewer cannot edit the codelist, then we display nothing
=> Only show download btn if downloadable

templates/_includes/header.html, templates/base-tw.html, templates/base.html
As `user` can be polluted when browsing users pages. This means the header can incorrectly display that a user has access to a "My Organisations" page, and sends the "is_admin" event incorrectly to Plausible.
=> Use `request.user` in base templates

assets/src/styles/base.css, opencodelists/tests/functional/test_build_codelist.py, opencodelists/tests/functional/test_docs_screenshots.py, templates/codelists/version.html
There are many options for which buttons should display in the sidebar of the versions template page. We should choose to be explicit, and make sure that anchor elements are outside of the form, and container elements are not shown if none of their children are visible.
=> Simplify logic for displaying buttons on template

codelists/actions.py
4d08d68 added a url param for forcing publishing of codelists updated via the API (defaulting to UNDER_REVIEW), but didn't add this logic to the codelist creation path.
This commit makes both these paths behave the same.
=> Unify publishing behaviour for new/updated codelists via API

codelists/api.py, codelists/tests/test_api.py
Fixes #2829 
A previous fix to avoid errors from codelists with no handles added a filter to the api to ensure only codelists with a single handle were returned. In fact a codelist can have multiple handles. This corrects the filter to limit to codelists with a `current` handle which better reflects the underlying models.
=> Fix API to return codelists with more than 1 handle
